import {studyTopics,topicReferences} from './study-guide.js';
import {readingSources} from './data/reading-sources.js';
import {historicalExams} from './data/exam-references.js';
import {createExamController,examFormFields,readExamRules,examRulesSummary} from './exam-ui.js';
import {legalContexts} from './data/legal-context.js';
import {programmes,programmeReferences} from './data/programmes.js';
import {learningState,lessonSession,dailyPathLesson,achievements,difficultyNames} from './learning.js';
import {testNotification,startReminders,shortcutGuide} from './notifications.js';
import {metrics,streak} from './analytics.js';
import {exportBackup,importBackup,downloadBackup} from './backup.js';
import {saveResponse} from './db.js';
import {getKV,setKV,allReviews,putReview,addAnswer,allAnswers,allCompetitions,putCompetition} from './db.js';
import {questions} from './data/questions.js';
import {articleCards,dueArticleCards,checkArticle,nextArticleMemory,articlePrompt} from './article-memory.js';
import {localDay,chooseEssayQuestion} from './essay.js';
import {guidedDailyLesson} from './guided-reading.js';
import {BEP_SOURCE,offerSummary,readCachedOffers,fetchOffers,notifyNewOffers,requestOfferPermission,offersShortcutGuide} from './offers.js';
import {legislation} from './data/legislation.js';
import {nextReview,buildSession,daysUntil,competitionPlan,eligible,examEligible,topicStages,administrationScope} from './engine.js';

const app=document.querySelector('#app');
const state={view:'home',pathPage:0,pathTrack:'exame',pathLaw:'crp',lessonId:null,dailyUnitId:null,dailyFinished:false,sessionAttempts:0,lastXPGain:0,profile:{region:'Madeira',area:'Recursos Humanos',administrationScope:'regional-ram',programme:'geral'},reviews:[],answers:[],competitions:[],session:[],index:0,answered:false,selected:null,onboarded:false,reminder:{enabled:false,time:'19:00'},articleRecall:{},articleReveal:null,essays:[]};
const nav=[['home','⌂','Hoje'],['path','◉','Percurso'],['progress','▥','Progresso'],['laws','§','Leis'],['competitions','◎','Concursos'],['settings','⚙','Definições']];

const exams=createExamController({questions,escapeHTML,shell,questionSource,currentView:()=>state.view,competitions:()=>state.competitions,reviews:()=>state.reviews,show:()=>{state.view='exam';render()},alert:message=>alert(message),updateRules:async(id,rules)=>{const c=state.competitions.find(c=>c.id===id);await putCompetition({...c,examRules:rules});state.competitions=await allCompetitions();render()},reloadAnswers:async()=>{state.answers=await allAnswers();state.reviews=await allReviews()}});
async function init(){
 state.onboarded=Boolean(await getKV('onboarded'));state.reminder=(await getKV('reminder'))||state.reminder;
 state.profile=(await getKV('profile'))||state.profile;state.profile.administrationScope=administrationScope(state.profile);state.profile.programme=state.profile.programme||'geral'; await setKV('profile',state.profile);
 state.reviews=await allReviews(); state.answers=await allAnswers(); state.competitions=await allCompetitions();state.articleRecall=(await getKV('articleRecall'))||{};state.essays=(await getKV('essayPractice'))||[];
 await exams.load();state.offersSettings=(await getKV('bepSettings'))||{enabled:false,scope:'rh'};state.offers=await readCachedOffers();
 if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js').catch(e=>console.error(e)); render();updateOffers();
}
function activeCompetition(){return state.competitions.find(c=>c.active)}
function calcAccuracy(){const ids=new Set(examPool().map(q=>q.id)),a=state.answers.filter(a=>ids.has(a.questionId));return a.length?Math.round(a.filter(a=>a.correct).length/a.length*100):null}
function selectedProgramme(){return programmes.find(p=>p.id===state.profile.programme)||programmes[0]}
function profilePool(){return eligible(questions,state.profile.region,selectedProgramme().laws,state.profile.area,administrationScope(state.profile),state.profile.programme)}
function examPool(){return examEligible(questions,state.profile.region,selectedProgramme().laws,state.profile.area,administrationScope(state.profile),state.profile.programme)}
function practisedArticles(){return articleCards(questions,state.answers,state.profile,selectedProgramme().laws)}
function dailyContext(){const c=activeCompetition();return {profile:c?{region:c.region||state.profile.region,area:c.area||state.profile.area,administrationScope:c.administrationScope||administrationScope(state.profile),programme:c.programme||state.profile.programme}:state.profile,laws:c?.legislationIds||selectedProgramme().laws}}
function todayLesson(){const {profile,laws}=dailyContext();return guidedDailyLesson(questions,state.answers,state.reviews,profile,laws,Date.now(),activeCompetition()?.weights||{})}
function todaySession(){return todayLesson().questions}
function startStudy(unitId=null){const lesson=todayLesson();if(unitId&&lesson.unit?.id!==unitId)return;if(!lesson.questions.length){state.view='path';render();return}state.lessonId=null;state.dailyUnitId=lesson.unit?.id||null;state.dailyFinished=false;state.sessionAttempts=0;state.session=lesson.questions;state.readingCount=lesson.readingCount;state.readingBlocks=lesson.readingBlocks;state.readingReady=lesson.readingCount===0;state.index=0;state.answered=false;state.selected=null;state.view='study';render()}
function navigate(v){if(v==='study')return startStudy();state.view=v;render()}
function shell(content){return `<div class="shell"><div class="brand"><img src="./icons/avatar.svg" alt="" width="44" height="44"><span>CONCURSO <b>STUDY</b></span><small>V0.2</small></div>${!state.onboarded?onboarding():''}${content}</div>${state.view!=='study'?bottomNav():''}`}
function bottomNav(){return `<nav class="bottom">${nav.map(([id,ico,label])=>`<button class="nav ${state.view===id?'active':''}" data-nav="${id}"><span class="ico">${ico}</span><span class="label">${label}</span></button>`).join('')}</nav>`}
function top(eyebrow,title){return `<header class="top"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1></div><span class="chip">${new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'short'}).format(new Date())}</span></header>`}
function readingBlock(block){return '<h3>'+escapeHTML(block.article)+' · '+escapeHTML(block.title||"")+'</h3>'+(block.isExcerpt?'<p class="eyebrow">Excerto · números '+escapeHTML(block.excerptParagraphs.join(", "))+'</p>':"")+'<div class="reading-text">'+escapeHTML(block.text)+'</div>'+(block.fullText?'<details><summary>Ler o artigo completo</summary><div class="reading-text">'+escapeHTML(block.fullText)+'</div></details>':"")+questionSource(block)}
function guidedReadingView(){return shell(top('Antes das perguntas','Leitura guiada')+'<section class="panel"><p>Lê a norma e responde a '+state.readingCount+' perguntas sobre o texto. Seguem-se '+(state.session.length-state.readingCount)+' perguntas de revisão e aplicação.</p>'+state.readingBlocks.map(readingBlock).join('')+'<button class="btn btn-dark" id="readingReady">Li o texto · responder</button></section>')}
function home(){const poolIds=new Set(examPool().map(q=>q.id)),lesson=todayLesson(),s=lesson.questions,acc=calcAccuracy(),due=state.reviews.filter(r=>new Date(r.dueAt)<=new Date()&&poolIds.has(r.questionId)).length,c=activeCompetition();return shell(`${top(`${escapeHTML(state.profile.area)} · ${escapeHTML(state.profile.region)}`,'Hoje')}
 <section class="hero"><img class="mascot" src="./icons/avatar.svg" alt="Guardião do conhecimento" width="130" height="130"><div><p class="eyebrow" style="color:#bbb">Lição diária do percurso</p><h2>${s.length} perguntas</h2><p>${escapeHTML(lesson.unit?.displayTitle||(lesson.revision?'Revisão do percurso':'Percurso concluído por agora'))} · ${s.length?lesson.readingCount+' sobre a leitura + '+lesson.generalCount+' de revisão e aplicação':'perguntas recentes voltam após seis horas'}</p></div><button class="btn btn-light" id="start" ${s.length?'':'disabled'}>${s.length?'Começar →':'Aguardar perguntas'}</button></section>
 <div class="stats"><div class="stat"><strong>${streak(state.answers)} ${streak(state.answers)===1?'dia':'dias'}</strong><span>dias consecutivos</span></div><div class="stat"><strong>${due}</strong><span>revisões</span></div><div class="stat"><strong>${acc!==null?acc+'%':'sem dados'}</strong><span>acerto</span></div></div>
 ${offersPanel()}${c?`<div class="panel"><p class="eyebrow">Concurso ativo</p><h3>${escapeHTML(c.title)}</h3><p class="muted">${escapeHTML(c.entity)} · ${daysUntil(c.examDate)} dias até à prova</p></div>`:''}
 <div class="section-title"><p class="eyebrow">Mapa de domínio</p><h3>Matérias principais</h3></div>
 <p class="muted">${escapeHTML(selectedProgramme().title)} · ${scopeName(administrationScope(state.profile))}</p>${journeyCard()}<section class="panel"><h3>Memorizar artigos</h3><p>${practisedArticles().length} artigos encontrados nas respostas. Escreve o número sem opções de escolha; a revisão volta no momento certo.</p><button class="btn btn-dark" data-nav="articles">Treinar artigos</button></section>${metricRows('law',examPool(),6)}<button class="btn" data-nav="progress">Ver progresso de todas as matérias</button><p class="muted">${examPool().length} perguntas de formato de prova disponíveis para as sessões diárias · ${questions.filter(q=>q.suspended).length} suspensas.</p>`)}
function study(){if(!state.lessonId&&!state.readingReady)return guidedReadingView();const q=state.session[state.index];if(!q)return sessionSummary();const law=legislation.find(l=>l.id===q.law);return shell(`<div class="quiz-top"><button class="btn btn-ghost" data-nav="home">Fechar</button><div class="meter"><span style="width:${((state.index+1)/state.session.length)*100}%"></span></div><span class="muted">${state.index+1}/${state.session.length}</span></div>${!state.lessonId?'<p class="eyebrow">'+(state.index<state.readingCount?'Leitura · pergunta '+(state.index+1)+' de '+state.readingCount:'Revisão e aplicação · pergunta '+(state.index-state.readingCount+1)+' de '+(state.session.length-state.readingCount))+'</p>':''}
 ${!state.lessonId&&state.index<state.readingCount?'<details class="panel"><summary>Consultar o texto</summary>'+state.readingBlocks.map(readingBlock).join('')+'</details>':''}
 <section class="quiz"><p class="eyebrow">${law?.short||''} · ${difficultyNames[q.difficulty]} · nível ${q.difficulty} · ${q.questionType==='calculo-ap'?'Cálculo de RH':q.questionType==='regra-ap'?'Regra jurídica':'Caso / interpretação'}</p><h2>${escapeHTML(q.prompt)}</h2><div class="options">${q.options.map((o,i)=>{let cls='option';if(state.answered){if(i===q.correct)cls+=' correct';else if(i===state.selected)cls+=' wrong'}return `<button class="${cls}" data-answer="${i}"><b>${String.fromCharCode(65+i)}</b>${escapeHTML(o)}</button>`}).join('')}</div>
 ${state.answered?`<div class="explain"><strong>Explicação${state.lastXPGain?` · +${state.lastXPGain} XP`:""}</strong><p class="feedback">${state.selected===q.correct?'Resposta correta':'Resposta incorreta'}</p><img class="feedback-avatar" src="./icons/avatar.svg" width="64" height="64" alt="Guardião do conhecimento"><p>${escapeHTML(q.explanation)}</p>${questionSource(q)}<button class="btn btn-dark" id="next">Continuar →</button></div>`:''}</section>`)}
function metricRows(dimension,pool=examPool(),limit=100){const rows=metrics(pool.filter(q=>!q.suspended),state.answers,dimension);return rows.slice(0,limit).map(g=>`<div class="panel"><strong>${escapeHTML(legislation.find(l=>l.id===g.key)?.short||(dimension==='difficulty'?difficultyNames[g.key]:g.key))}</strong><div class="coverage" aria-label="Cobertura ${g.coverage}%"><span style="width:${g.coverage}%"></span></div><p>${g.seen}/${g.total} perguntas vistas · ${g.attempts} respostas${g.assistedAttempts?' ('+g.assistedAttempts+' com leitura)':''} · acerto ${g.accuracy===null?'sem dados':g.accuracy+'%'} · domínio sem leitura ${g.mastery===null?'sem dados':g.mastery+'%'}</p></div>`).join('')+(rows.length>limit&&limit===100?'<p>Mostrados 100 grupos. Seleciona um diploma para detalhar os subtemas; o inventário completo está na matriz de cobertura.</p>':'')}
function progress(){const pool=examPool().filter(q=>state.progressLaw==='all'||q.law===state.progressLaw),stages=[...topicStages(pool,state.answers).values()];return shell(top('Respostas registadas','Progresso')+'<p>Estes valores usam as perguntas de formato de prova. Domínio recente: acerto ponderado com meia-vida de 30 dias. Perguntas vistas mede o treino; não mede a cobertura integral da lei.</p><label>Filtrar diploma<select id="progressLaw"><option value="all">Todos os diplomas do perfil</option>'+legislation.filter(l=>examPool().some(q=>q.law===l.id)).map(l=>'<option value="'+l.id+'" '+(l.id===state.progressLaw?'selected':'')+'>'+escapeHTML(l.short)+'</option>').join('')+'</select></label><h2>Dificuldade atual por tema</h2><p>O próximo nível desbloqueia quando as perguntas disponíveis no nível atual estiverem dominadas: até três distintas corretas e pelo menos 80% de acerto nesse nível. A mudança entra na sessão seguinte.</p>'+stages.slice(0,100).map(s=>'<div class="panel"><strong>'+escapeHTML(legislation.find(l=>l.id===s.law)?.short||s.law)+' · '+escapeHTML(s.topic)+'</strong><p>Nível atual '+s.stage+' de '+s.max+'</p></div>').join('')+['law','topic','subtopic','difficulty'].map((d,i)=>'<h2>'+['Diploma','Tema','Subtema','Dificuldade'][i]+'</h2>'+metricRows(d,pool)).join('')+'<h2>Respostas de desenvolvimento</h2><p>'+state.essays.length+' respostas guardadas neste dispositivo e no backup.</p>'+state.essays.slice(-5).reverse().map(e=>'<div class="panel"><strong>'+escapeHTML(e.day)+' · '+escapeHTML(legislation.find(l=>l.id===e.law)?.short||e.law)+'</strong><p>'+escapeHTML(e.text)+'</p></div>').join(''))}
function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function programmeLawLabel(id){const p=selectedProgramme();return p.requiredLaws?.includes(id)?"Matéria do aviso — legislação atual":p.complementaryLaws?.includes(id)?"Complemento de RH geral":""}
function laws(){const pool=profilePool();return shell(`${top('Base jurídica','Legislação')}<section class="panel"><h3>${escapeHTML(selectedProgramme().title)}</h3><p>${escapeHTML(selectedProgramme().description)}</p><button class="btn btn-dark" data-nav="articles">Treinar números dos artigos</button><p><a class="btn" href="./cobertura.html">Abrir matriz de cobertura e fontes</a></p><p>A matriz indica os artigos com perguntas, os casos de RH e as matérias ainda sem treino. Não certifica cobertura integral.</p></section>${studyGuideView(pool)}<div class="grid">${legislation.filter(l=>pool.some(q=>q.law===l.id)).map(l=>`<div class="panel law"><p class="eyebrow">${escapeHTML(l.region)}</p><p class="muted">${escapeHTML(programmeLawLabel(l.id))}</p><h3>${escapeHTML(l.short)}</h3><div>${escapeHTML(l.title)}</div><small>${escapeHTML(l.diploma)}</small><div class="status">${lawStatus(l)}</div></div>`).join('')}</div><section class="panel"><h3>Programas consultados</h3>${programmeReferences.map(r=>'<p><a href="'+escapeHTML(r.source)+'" target="_blank" rel="noopener">'+escapeHTML(r.entity)+' · '+escapeHTML(r.code)+'</a><br>'+escapeHTML(r.notes)+'</p>').join('')}</section>`)} 
function articleView(){const cards=practisedArticles(),due=dueArticleCards(cards,state.articleRecall),record=state.articleReveal,card=record?.card||due[0];let body=top('Recordação ativa','Artigos')+'<p>Escreve o número do artigo que fundamenta uma pergunta já respondida. A referência aparece após a tentativa. A revisão não altera a nota nem o XP da pergunta.</p><p>'+cards.length+' artigos encontrados · '+due.length+' para rever agora.</p>';
 if(!card)body+='<section class="panel"><h3>Sem artigos para rever agora</h3><p>Responde a uma pergunta diária para acrescentar o respetivo artigo, ou regressa quando a próxima revisão estiver disponível.</p><button class="btn btn-dark" data-nav="home">Voltar a Hoje</button></section>';
 else{const law=legislation.find(l=>l.id===card.law);body+='<section class="panel"><p class="eyebrow">'+escapeHTML(law?.short||card.law)+' · '+escapeHTML(card.question.subtopic||card.question.topic)+'</p><h3>Qual é o artigo que fundamenta esta regra?</h3><p>'+escapeHTML(articlePrompt(card.question))+'</p>'+(record?'<p class="feedback">'+(record.correct?'Número correto.':'Número incorreto.')+'</p><p>Referência: <strong>'+escapeHTML(card.article)+'</strong></p>'+questionSource(card.question)+'<p>A próxima revisão é agendada conforme o resultado.</p><button class="btn btn-dark" id="nextArticle">Próximo artigo</button>':'<form id="articleForm"><label>Número do artigo (ex.: 202 ou 97-A)<input name="articleNumber" required autocomplete="off" inputmode="text"/></label><button class="btn btn-dark">Verificar e revelar</button></form>')+'</section>'}
 return shell(body+'<button class="btn" data-nav="home">Voltar a Hoje</button>')}
function competitions(){const items=state.competitions.map(c=>`<div class="panel"><p class="eyebrow">${c.active?'Ativo':'Arquivado'}</p><h3>${escapeHTML(c.title)}</h3><p>${escapeHTML(c.entity)}</p>${competitionSummary(c)}${examRulesSummary(c,escapeHTML)}${exams.historySummary(c)}<form class="form" data-exam-rules-form="${escapeHTML(c.id)}">${examFormFields(escapeHTML,c.examRules)}<button class="btn" type="submit">Guardar regras neste concurso</button></form>${c.active?`<button class="btn btn-dark" data-exam="${escapeHTML(c.id)}">Abrir ou retomar simulado</button>`:""}<button class="btn" data-activate="${escapeHTML(c.id)}">${c.active?'Arquivar':'Ativar'}</button></div>`).join('');return shell(`${top('Preparação específica','Concursos')}${exams.pendingSummary()}<div class="panel"><h3>Adicionar concurso</h3><form class="form" id="competitionForm"><label>Cargo / vaga</label><input name="title" required placeholder="Técnico Superior — RH"/><label>Entidade</label><input name="entity" required placeholder="Direção Regional de Educação"/><label>Data da prova</label><input name="examDate" required type="date"/><label>Legislação (seleciona pelo menos uma)</label><select name="laws" multiple size="6">${legislation.filter(l=>profilePool().some(q=>q.law===l.id)).map(l=>`<option value="${l.id}">${l.short} — ${l.title}</option>`).join('')}</select><details><summary>Prioridade das matérias (opcional)</summary><p>Pesos por diploma (1–10)</p>${legislation.filter(l=>profilePool().some(q=>q.law===l.id)).map(l=>`<label>${l.short}<input type="number" min="1" max="10" value="1" name="weight-${l.id}"></label>`).join('')}</details>${examFormFields(escapeHTML)}<button class="btn btn-dark" style="margin-top:14px">Guardar concurso</button></form></div>${items}${examResearchView()}`)}
function settings(){return shell(`${top('Aplicação','Definições')}<div class="panel"><h3>Perfil</h3><form class="form" id="profileForm"><label>Região</label><select name="region"><option ${state.profile.region==='Madeira'?'selected':''}>Madeira</option><option ${state.profile.region==='Continente'?'selected':''}>Continente</option><option ${state.profile.region==='Açores'?'selected':''}>Açores</option></select><label>Âmbito administrativo</label><select name="scope">${['central','local','regional-ram'].map(id=>`<option value="${id}" ${administrationScope(state.profile)===id?'selected':''}>${scopeName(id)}</option>`).join('')}</select><label>Programa de estudo</label><select name="programme">${programmes.map(p=>`<option value="${p.id}" ${state.profile.programme===p.id?'selected':''}>${escapeHTML(p.title)}</option>`).join('')}</select><p class="muted">${escapeHTML(selectedProgramme().description)}</p><label>Área</label><select name="area"><option ${state.profile.area==='Recursos Humanos'?'selected':''}>Recursos Humanos</option>${['Gestão Financeira','Administração','Educação','Jurídico'].map(area=>`<option ${state.profile.area===area?'selected':''}>${area}</option>`).join('')}</select><button class="btn btn-dark" style="margin-top:14px">Guardar</button></form></div><div class="panel"><h3>Dados locais</h3><p class="muted">O backup inclui perfil, respostas, revisões, concursos e todas as chaves locais. Importar substitui os dados atuais.</p><button class="btn" id="exportBackup">Exportar backup</button><label>Importar JSON<input type="file" id="importBackup" accept="application/json,.json"></label></div>${reminderPanel()}${offersSettingsPanel()}`)}
function render(){app.innerHTML=state.view==='exam'?exams.view():state.view==='path'?pathView():state.view==='home'?home():state.view==='study'?study():state.view==='articles'?articleView():state.view==='progress'?progress():state.view==='laws'?laws():state.view==='competitions'?competitions():settings();bind()}
function bind(){
 exams.bind();
 document.querySelectorAll('[data-guide-reference]').forEach(b=>b.onclick=()=>{state.guideReference=b.dataset.guideReference;render()});
 exams.bind();
 document.querySelector('#refreshOffers')?.addEventListener('click',()=>updateOffers(true));
 document.querySelector('#offersForm')?.addEventListener('submit',async e=>{e.preventDefault();const settings={enabled:e.target.elements.enabled.checked,scope:e.target.elements.scope.value};const enabling=settings.enabled&&!state.offersSettings.enabled;const changing=state.offersSettings.scope!==settings.scope;try{if(enabling)state.offersPermission=await requestOfferPermission();if(enabling||changing)await setKV('bepSeen',state.offers?.offers.map(o=>o.id)||[]);await setKV('bepSettings',settings);state.offersSettings=settings;render()}catch(err){alert('Não foi possível guardar os alertas: '+err.message)}});
 document.querySelector('#readingReady')?.addEventListener('click',()=>{state.readingReady=true;render()});
 document.querySelector('#essayForm')?.addEventListener('submit',async e=>{e.preventDefault();const q=chooseEssayQuestion(state.session),day=localDay(),value=new FormData(e.target).get('essay')?.trim();if(!q||!value||value.length<80)return;const next=[...state.essays,{day,questionId:q.id,law:q.law,competitionId:activeCompetition()?.id||null,text:value,savedAt:new Date().toISOString()}];try{await setKV('essayPractice',next);state.essays=next;render()}catch(err){alert('Resposta escrita não guardada: '+err.message)}});
 document.querySelector('#articleForm')?.addEventListener('submit',async e=>{e.preventDefault();const card=dueArticleCards(practisedArticles(),state.articleRecall)[0];if(!card)return;const correct=checkArticle(new FormData(e.target).get('articleNumber'),card);const next={...state.articleRecall,[card.key]:nextArticleMemory(state.articleRecall[card.key],correct)};try{await setKV('articleRecall',next);state.articleRecall=next;state.articleReveal={card,correct};render()}catch(err){alert('Revisão não guardada: '+err.message)}});
 document.querySelector('#nextArticle')?.addEventListener('click',()=>{state.articleReveal=null;render()});
 document.querySelectorAll('[data-path-track]').forEach(b=>b.onclick=()=>{state.pathTrack=b.dataset.pathTrack;state.pathPage=0;render();window.scrollTo(0,0)});
 document.querySelectorAll('[data-daily-unit]').forEach(b=>b.onclick=()=>startStudy(b.dataset.dailyUnit));
 document.querySelectorAll('[data-path-page]').forEach(b=>b.onclick=()=>{state.pathPage=Number(b.dataset.pathPage);render();window.scrollTo(0,0)});
 document.querySelector('#pathNextAvailable')?.addEventListener('click',()=>{const list=journey().units.filter(u=>u.law===state.pathLaw),index=list.findIndex(u=>u.unlocked&&!u.passed);state.pathPage=Math.max(0,Math.floor(index/20));render();window.scrollTo(0,0)});
 document.querySelector('#progressLaw')?.addEventListener('change',e=>{state.progressLaw=e.target.value;render()});
 document.querySelectorAll('[data-path-law]').forEach(b=>b.onclick=()=>{state.pathLaw=b.dataset.pathLaw;state.pathPage=0;state.view='path';render()});
 document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>startLesson(b.dataset.lesson));
 document.querySelector('#finishOnboarding')?.addEventListener('click',async()=>{await setKV('onboarded',true);state.onboarded=true;render()});
 document.querySelector('#testNotification')?.addEventListener('click',()=>testNotification().catch(e=>alert(e.message)));
 document.querySelector('#reminderForm')?.addEventListener('submit',async e=>{e.preventDefault();state.reminder={enabled:e.target.elements.enabled.checked,time:e.target.elements.time.value};await setKV('reminder',state.reminder);render()});

 document.querySelector('#exportBackup')?.addEventListener('click',async()=>{try{downloadBackup(await exportBackup())}catch(e){alert(e.message)}});
 document.querySelector('#importBackup')?.addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>50*1024*1024)throw Error('Limite: 50 MB.');const b=JSON.parse(await file.text());const {validateBackup}=await import('./backup.js');validateBackup(b);if(!confirm('Substituir todos os dados locais pelo backup? Será descarregada uma cópia dos dados atuais.'))return;downloadBackup(await exportBackup());await importBackup(b);await init();}catch(err){alert('Não foi possível importar: '+err.message)}});
 document.querySelectorAll('[data-activate]').forEach(b=>b.onclick=async()=>{const target=state.competitions.find(c=>c.id===b.dataset.activate),active=!target.active;for(const c of state.competitions){c.active=c.id===target.id&&active;await putCompetition(c)}render()});
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));document.querySelector('#start')?.addEventListener('click',()=>startStudy());document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.answer)));document.querySelector('#next')?.addEventListener('click',()=>{state.index++;if(!state.lessonId&&state.index>=state.session.length&&state.sessionAttempts)state.dailyFinished=true;state.answered=false;state.selected=null;render()});
 document.querySelector('#profileForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const p=programmes.find(p=>p.id===f.get('programme'));state.profile={region:p?.region||f.get('region'),area:f.get('area'),administrationScope:p?.scope||f.get('scope'),programme:p?.id||'geral'};if(state.profile.region!=='Madeira'&&state.profile.administrationScope==='regional-ram'){alert('A adaptação regional da Madeira exige a região Madeira.');return}await setKV('profile',state.profile);render()});
 document.querySelector('#competitionForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const selected=[...e.target.elements.laws.selectedOptions].map(o=>o.value);if(!selected.length){alert('Seleciona pelo menos um diploma.');return}const weights=Object.fromEntries(selected.map(id=>[id,Number(f.get('weight-'+id))||1]));for(const c of state.competitions){if(c.active){c.active=false;await putCompetition(c)}}const c={id:crypto.randomUUID(),title:f.get('title'),entity:f.get('entity'),examDate:f.get('examDate'),region:state.profile.region,area:state.profile.area,administrationScope:administrationScope(state.profile),programme:state.profile.programme,legislationIds:selected,weights,examRules:readExamRules(e.target),active:true,createdAt:new Date().toISOString()};await putCompetition(c);state.competitions=await allCompetitions();render()});}
function competitionSummary(c){const p=competitionPlan(c,questions,state.answers,state.profile.region);return '<p>'+ (p.days===null?'Data inválida':p.days<0?'Prova passada':p.days===0?'Prova hoje':p.days+' dias até à prova')+' · '+p.total+' perguntas de formato de prova</p><p>Plano: '+p.daily+' perguntas/dia como meta de cobertura. A sessão diária tem duas perguntas de leitura e oito de revisão ou aplicação. Se a meta for superior a dez, completa-a nas lições desbloqueadas do percurso. O intervalo de repetição pode reduzir as perguntas disponíveis.</p>'+metricRows('law',examEligible(questions,c.region||state.profile.region,c.legislationIds,c.area,c.administrationScope||administrationScope(state.profile),c.programme))}
async function answer(i){if(state.answered)return;state.answered=true;const q=state.session[state.index],correct=i===q.correct,xpBefore=journey().xp;try{await saveResponse({questionId:q.id,correct,selected:i,lessonId:state.lessonId,mode:state.lessonId?"lesson":state.index<state.readingCount?"guided-reading":"daily",assisted:!state.lessonId&&state.index<state.readingCount,familyId:q.familyId||q.id,competitionId:activeCompetition()?.id||null,answeredAt:new Date().toISOString()},nextReview(state.reviews.find(r=>r.questionId===q.id),correct,q.id));state.selected=i;state.reviews=await allReviews();state.answers=await allAnswers();state.sessionAttempts++;state.lastXPGain=journey().xp-xpBefore;render()}catch(e){state.answered=false;alert('Resposta não guardada: '+e.message)}}
startReminders(()=>{const banner=document.createElement('div');banner.className='reminder-banner';banner.setAttribute('role','status');banner.textContent='Hora de estudar. Abre Hoje para iniciar a sessão diária.';document.querySelector('#app').prepend(banner)});
init().catch(e=>{app.textContent='Não foi possível abrir os dados locais: '+e.message});



function onboarding(){return '<section class="onboarding"><img src="./icons/avatar.svg" alt="" width="90" height="90"><div><p class="eyebrow">Preparação diária</p><h2>Estuda com método.</h2><p>Escolhe a região, responde à sessão e acompanha o progresso. Os dados ficam neste dispositivo: exporta um backup regularmente.</p><button class="btn btn-dark" id="finishOnboarding">Começar</button></div></section>'}
function safeSource(url){try{const u=new URL(url);return u.protocol==='https:'&&['diariodarepublica.pt','www.parlamento.pt','eur-lex.europa.eu','joram.madeira.gov.pt','pgdlisboa.pt','www.pgdlisboa.pt','www.madeira.gov.pt','www.cnpd.pt','www.cada.pt','www.dgaep.gov.pt','www.adse.pt','www2.adse.pt','www.cga.pt','cga.pt','files.diariodarepublica.pt','www.tribunalconstitucional.pt','www.edpb.europa.eu','www.cne.pt'].includes(u.hostname)?escapeHTML(u.href):null}catch{return null}}
function questionSource(q){const url=safeSource(q.officialSource),context=legalContexts[q.law+':'+String(q.articleNumber||'')];const note=q.legalContext||context?.text,sources=q.relatedSources||context?.sources||[];return '<div class="legal">'+escapeHTML(q.article)+' · '+escapeHTML(q.legalVersion||'Versão por confirmar')+'<br>Conferência do texto: '+escapeHTML(q.lastValidated||'não realizada')+(url?' · <a href="'+url+'" target="_blank" rel="noopener">Consultar fonte oficial</a>':'')+'</div>'+(note?'<aside class="legal-context"><strong>Aplicação da norma</strong><p>'+escapeHTML(note)+'</p>'+sources.map(source=>{const link=safeSource(source.url);return link?'<a href="'+link+'" target="_blank" rel="noopener">'+escapeHTML(source.title)+'</a>':''}).filter(Boolean).join(' · ')+'</aside>':'')}
function lawStatus(l){const items=profilePool().filter(q=>q.law===l.id),source=items.find(q=>safeSource(q.officialSource));return items.length+' perguntas de escolha múltipla'+(source?' · <a href="'+safeSource(source.officialSource)+'" target="_blank" rel="noopener">Fonte oficial</a>':' · aguarda validação da legislação aplicável')}
function reminderPanel(){return '<section class="panel"><h3>Lembretes</h3><p>Enquanto a aplicação estiver aberta, mostra um lembrete à hora escolhida. Com a app fechada, configura a automação nos Atalhos.</p><form class="form" id="reminderForm"><label><input name="enabled" type="checkbox" '+(state.reminder.enabled?'checked':'')+'> Lembrete na aplicação</label><label>Hora local<input name="time" type="time" required value="'+escapeHTML(state.reminder.time)+'"></label><button class="btn btn-dark">Guardar lembrete</button></form><button class="btn" id="testNotification">Testar notificação do dispositivo</button><details><summary>Configurar Atalhos no iPhone</summary>'+shortcutGuide()+'<p>Endereço da app: <code>'+escapeHTML(typeof location==='undefined'?'endereço do GitHub Pages':location.href.split('#')[0])+'</code></p><p>No iPhone, o teste de notificação pode exigir a app adicionada ao ecrã principal e permissão do sistema.</p></details></section>'}


function journey(){return learningState(questions,state.answers,state.profile,selectedProgramme().laws)}
function journeyCard(){const p=journey(),exam=p.units.filter(u=>u.track==='exame');return '<section class="panel journey-card"><p class="eyebrow">Percurso de aprendizagem</p><h3>Nível '+p.level+' · '+p.xp+' XP</h3><p>'+exam.filter(u=>u.passed).length+'/'+exam.length+' lições de prova concluídas · '+p.nextLevelXP+' XP até ao próximo nível</p><div class="coverage" aria-label="Progresso do nível"><span style="width:'+((p.xp%200)/2)+'%"></span></div>'+(state.view==='path'?'':'<button class="btn btn-dark" data-nav="path">Abrir percurso</button>')+'</section>'}
function scopeName(id){return {'central':'Administração central — regime nacional','local':'Autarquias — regime autárquico','regional-ram':'Administração regional da Madeira'}[id]||id}
function pathView(){if(state.pathTrack==='exame')return examPathView();const p=journey(),laws=legislation.filter(l=>p.units.some(u=>u.law===l.id));if(!laws.some(l=>l.id===state.pathLaw))state.pathLaw=laws[0]?.id;const allUnits=p.units.filter(u=>u.law===state.pathLaw);state.pathPage=Math.min(state.pathPage,Math.max(0,Math.ceil(allUnits.length/20)-1));const units=allUnits.slice(state.pathPage*20,state.pathPage*20+20);return shell(top('Aprender por etapas','Percurso')+'<button class="btn btn-dark" data-path-track="exame">Plano diário em mapa</button>'+journeyCard()+'<p>Responde a todas as perguntas da unidade e acerta em pelo menos 80% para avançar. A primeira resposta correta de cada pergunta vale 12–20 XP, conforme a dificuldade. O estudo diário também conta.</p><div class="law-tabs">'+laws.map(l=>'<button class="btn '+(l.id===state.pathLaw?'btn-dark':'')+'" data-path-law="'+l.id+'">'+l.short+'</button>').join('')+'</div><div class="panel"><button class="btn" id="pathNextAvailable">Ir para a próxima unidade disponível</button><p>Página '+(state.pathPage+1)+'/'+Math.max(1,Math.ceil(allUnits.length/20))+' · '+allUnits.length+' unidades neste diploma</p>'+pathPagination(allUnits.length)+'</div><div class="roadmap">'+units.map((u,i)=>'<article class="road-unit '+(u.passed?'passed':u.unlocked?'available':'locked')+'"><div class="unit-number">'+(u.passed?'✓':state.pathPage*20+i+1)+'</div><div><p class="eyebrow">'+'Percurso original'+' · Nível de dificuldade '+u.difficulty+'</p><h3>'+escapeHTML(u.title)+'</h3><p>'+u.seen+'/'+u.total+' vistas · '+u.correct+'/'+u.total+' corretas na última tentativa</p><p class="muted">Meta: '+u.required+' respostas corretas e todas vistas.</p><button class="btn '+(u.unlocked?'btn-dark':'')+'" data-lesson="'+u.id+'" '+(!u.unlocked?'disabled':'')+'>'+(u.passed?'Rever unidade':u.unlocked?'Iniciar unidade':'Concluir a unidade anterior')+'</button></div></article>').join('')+'</div>'+pathPagination(allUnits.length)+'<section class="panel"><h3>Marcos</h3><div class="badges">'+achievements(p).map(a=>'<span class="badge '+(a.earned?'earned':'')+'">'+escapeHTML(a.name)+'</span>').join('')+'</div></section>')}
function examPathView(){const {profile,laws}=dailyContext(),p=learningState(questions,state.answers,profile,laws),units=p.units.filter(u=>u.track==='exame'),current=units.find(u=>u.unlocked&&!u.passed),finished=units.filter(u=>u.passed).length,canStart=todayLesson().questions.length>0;let chapter=0;
 const nodes=units.map((u,i)=>{let marker='';if(u.chapterNumber!==chapter){chapter=u.chapterNumber;marker='<div class="chapter-banner">Capítulo '+chapter+' · '+escapeHTML(u.chapterTitle)+'</div>'}
 const status=u.passed?'done':u.id===current?.id?'current':'locked',button=status==='locked'?'<span class="path-node" aria-hidden="true">'+(i+1)+'</span>':'<button class="path-node" '+(status==='done'?'data-lesson="'+escapeHTML(u.id)+'"':'data-daily-unit="'+escapeHTML(u.id)+'"')+' aria-label="'+escapeHTML(u.displayTitle)+' · '+(status==='done'?'concluída':'disponível')+'">'+(status==='done'?'✓':i+1)+'</button>';
 return marker+'<div class="path-step '+status+'" id="step-'+escapeHTML(u.id)+'"><div class="path-rail"></div>'+button+(status==='current'?'<div class="path-popover"><p class="eyebrow">Próxima lição</p><strong>'+escapeHTML(u.displayTitle)+'</strong><p>'+u.seen+'/'+u.total+' regras praticadas · meta '+u.required+' corretas</p><p>'+u.variantCount+' perguntas disponíveis para estas regras</p><button class="btn btn-dark" data-daily-unit="'+escapeHTML(u.id)+'" '+(canStart?'':'disabled')+'>'+(canStart?'Começar lição':'Aguardar revisão após seis horas')+'</button></div>':'<span class="path-caption">'+escapeHTML(u.displayTitle)+'</span>')+'</div>'}).join('');
 return shell(top('Aprender por etapas','Percurso')+'<section class="panel path-progress"><strong>'+finished+'/'+units.length+' lições concluídas</strong><p>A sessão diária começa por leitura guiada e duas perguntas, seguidas de oito perguntas de revisão e aplicação. Uma lição pode exigir mais de uma sessão. Uma pergunta por regra em cada sessão; variantes diferentes regressam nas revisões. Pratica todas e acerta em pelo menos 80% para avançar.</p><div class="coverage" aria-label="Progresso das lições"><span style="width:'+(units.length?Math.round(100*finished/units.length):0)+'%"></span></div></section>'+dailyEssay()+(!current?'<section class="panel"><h3>Revisão do percurso</h3><p>O mapa foi concluído. Continua com novas variantes e revisões adaptadas ao teu histórico.</p><button class="btn btn-dark" data-nav="study">Continuar a praticar</button></section>':'')+'<div class="path-map">'+nodes+'</div><section class="panel"><h3>Unidades anteriores</h3><p>As unidades anteriores de escolha múltipla conservam o histórico.</p><button class="btn" data-path-track="outros">Abrir percurso anterior</button></section>')}
function startLesson(id){const unit=journey().units.find(u=>u.id===id);if(!unit?.unlocked)return;const session=lessonSession(unit,state.answers);if(!session.length){const times=unit.questions.map(q=>journey().latest.get(q.id)).filter(Boolean).map(a=>Date.parse(a.answeredAt)+6*3600000);alert('Estas perguntas foram respondidas recentemente. A próxima fica disponível em '+new Date(Math.min(...times)).toLocaleString('pt-PT')+'. Podes avançar noutra matéria.');return}state.lessonId=id;state.sessionAttempts=0;state.session=session;state.index=0;state.answered=false;state.selected=null;state.lastXPGain=0;state.view='study';render()}
function sessionSummary(){const p=journey(),unit=p.units.find(u=>u.id===state.lessonId);if(unit){const next=p.units.find(u=>u.law===unit.law&&u.unlocked&&!u.passed);return shell('<section class="empty"><h2>'+(unit.passed?'Unidade concluída':'Sessão da unidade terminada')+'</h2><p>'+unit.seen+'/'+unit.total+' perguntas vistas · '+unit.correct+' respostas corretas na última tentativa.</p><p>'+(unit.passed?'O marco foi alcançado.':'Para concluir: todas vistas e pelo menos '+unit.required+' corretas. As perguntas respondidas ficam disponíveis novamente após 6 horas.')+'</p><p>Nível '+p.level+' · '+p.xp+' XP</p>'+(next&&next.id!==unit.id?'<button class="btn btn-dark" data-lesson="'+next.id+'">Próxima unidade</button>':'')+'<button class="btn" data-nav="path">Voltar ao percurso</button></section>')}return shell('<section class="empty"><h2>'+(state.sessionAttempts?'Lição terminada':'Sem perguntas disponíveis agora')+'</h2><p>'+state.sessionAttempts+' respostas guardadas nesta lição.</p>'+(!state.sessionAttempts?'<p>As perguntas recentes voltam após 6 horas. Consulta o percurso para estudar outra matéria.</p>':'<p>O percurso mostra o avanço. Com um concurso ativo, podes escrever a resposta de desenvolvimento de hoje.</p>')+'<button class="btn btn-dark" data-nav="path">Ver percurso</button><button class="btn" data-nav="articles">Treinar artigos</button></section>'+dailyEssay())}
function dailyEssay(){const day=localDay(),saved=state.essays.find(e=>e.day===day);if(!saved&&(!activeCompetition()||!state.dailyFinished||state.lessonId))return '';const q=saved?questions.find(q=>q.id===saved.questionId):chooseEssayQuestion(state.session);if(!q)return '';
 return '<section class="panel"><p class="eyebrow">Uma vez por dia · resposta de desenvolvimento</p><h3>Explica e fundamenta</h3><p>'+escapeHTML(articlePrompt(q))+'</p><p>Escreve 5 a 8 linhas: identifica o problema, apresenta a regra, aplica-a à situação e conclui. Indica o artigo se o souberes.</p>'+(saved?'<p><strong>Resposta guardada</strong></p><p>'+escapeHTML(saved.text)+'</p><h3>Conferência</h3><p>'+escapeHTML(q.explanation)+'</p>'+questionSource(q)+'<p>Confere se a tua resposta identificou o problema, citou a regra, aplicou a norma aos factos e chegou a uma conclusão. A aplicação não atribui nota automática à escrita.</p>':'<form id="essayForm"><label>A tua resposta<textarea name="essay" rows="8" minlength="80" maxlength="5000" required></textarea></label><button class="btn btn-dark">Guardar e ver critérios</button></form>')+'</section>'}

function pathPagination(total){return '<div class="panel"><button class="btn" data-path-page="'+(state.pathPage-1)+'" '+(state.pathPage===0?'disabled':'')+'>Anterior</button> <button class="btn" data-path-page="'+(state.pathPage+1)+'" '+((state.pathPage+1)*20>=total?'disabled':'')+'>Seguinte</button></div>'}

let offersBusy=false,lastOffersRequest=0;
async function updateOffers(force=false){
 if(offersBusy||(!force&&Date.now()-lastOffersRequest<5*60000))return;
 offersBusy=true;lastOffersRequest=Date.now();state.offersBusy=true;
 try{state.offers=await fetchOffers();state.offersOffline=false;state.newOffers=await notifyNewOffers(state.offers,state.offersSettings);}catch{state.offersOffline=true;}
 finally{offersBusy=false;state.offersBusy=false;if(['home','settings'].includes(state.view))render();}
}
function offerItems(items){return '<ul class="offer-list">'+items.map(o=>'<li><a href="'+escapeHTML(o.url)+'" target="_blank" rel="noopener noreferrer">'+escapeHTML(o.code)+' · '+escapeHTML(o.career)+'</a><p>'+escapeHTML(o.organisation)+'</p><p class="muted">Candidatura até '+new Date(o.deadline+'T12:00:00Z').toLocaleDateString('pt-PT')+' · '+(o.rh==='yes'?'Funções de RH identificadas':o.rh==='unknown'?'Área por verificar':escapeHTML(o.functionalArea))+'</p></li>').join('')+'</ul>';}
function offersPanel(){
 const s=offerSummary(state.offers),last=state.offers?.checkedAt?new Date(state.offers.checkedAt).toLocaleString('pt-PT',{timeZone:'Europe/Lisbon'}):null;
 const heading=!s.hasVerification?'A aguardar verificação':s.stale||s.error?'Última informação disponível':s.rh.length?s.rh.length+' '+(s.rh.length===1?'oferta de RH':'ofertas de RH'):'Sem ofertas de RH identificadas';
 const message=s.hasVerification?(s.offers.length+' ofertas sem vínculo com prazo aberto na última verificação'+(s.unknown.length?' · '+s.unknown.length+' por classificar':'')+'.'):'Ainda não foi possível confirmar as ofertas. Consulta diretamente a BEP-RAM.';
 const other=s.offers.filter(o=>o.rh==='no'),unknown=s.unknown;
 return '<section class="panel" id="bepOffers"><p class="eyebrow">BEP-RAM · cidadãos sem vínculo</p><h3>'+heading+'</h3><p>'+message+'</p>'+(state.newOffers?'<p role="status"><strong>'+state.newOffers+' novas ofertas para consultar desde a última verificação na aplicação.</strong></p>':'')+(s.rh.length?offerItems(s.rh):'')+(unknown.length?'<details><summary>Ofertas por verificar ('+unknown.length+')</summary>'+offerItems(unknown)+'</details>':'')+(other.length?'<details><summary>Outras ofertas sem vínculo ('+other.length+')</summary>'+offerItems(other)+'</details>':'')+(last?'<p class="muted">Fonte verificada em '+last+'.</p>':'')+(s.stale||s.error?'<p class="muted">A informação pode estar desatualizada; uma falha de atualização não significa ausência de ofertas.</p>':'')+(state.offersOffline?'<p class="muted">Sem atualização pela internet nesta abertura. Mantém-se a informação guardada.</p>':'')+'<button class="btn" id="refreshOffers" '+(state.offersBusy?'disabled':'')+'>'+(state.offersBusy?'A verificar…':'Atualizar painel')+'</button> <a class="btn" href="'+BEP_SOURCE+'" target="_blank" rel="noopener noreferrer">Consultar BEP-RAM</a><p class="muted">A classificação de RH usa a área e as funções publicadas. Confirma requisitos, habilitações e prazo no aviso.</p></section>';
}
function offersSettingsPanel(){
 const settings=state.offersSettings||{enabled:false,scope:'rh'},url=typeof location!=='undefined'?new URL('./data/bep-offers.json',location.href).href:'endereço da aplicação seguido de data/bep-offers.json';
 return '<section class="panel"><h3>Alertas BEP-RAM</h3><p>O painel Hoje mostra ofertas para cidadãos sem vínculo. A aplicação verifica os dados ao abrir e enquanto está visível. Com a aplicação fechada, usa a automação nos Atalhos.</p><form id="offersForm" class="form"><label><input type="checkbox" name="enabled" '+(settings.enabled?'checked':'')+'> Avisar quando surgirem novas ofertas ao abrir a aplicação</label><label>Ofertas a avisar<select name="scope"><option value="rh" '+(settings.scope==='rh'?'selected':'')+'>RH e ofertas com área por verificar</option><option value="all" '+(settings.scope==='all'?'selected':'')+'>Todas as ofertas sem vínculo</option></select></label><button class="btn btn-dark">Guardar alertas</button></form>'+(settings.enabled&&state.offersPermission===false?'<p>Os avisos continuam no painel. A notificação do dispositivo não foi autorizada ou está indisponível.</p>':'')+'<details><summary>Alertas com a app fechada no iPhone</summary>'+offersShortcutGuide()+'<p>Endereço das ofertas: <code>'+escapeHTML(url)+'</code></p></details><p class="muted">A publicação precisa de ter a atualização BEP-RAM ativa no GitHub. O painel mostra sempre a data da última consulta à fonte.</p></section>';
}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')updateOffers();});
setInterval(()=>{if(document.visibilityState==='visible')updateOffers();},15*60000);

function studyGuideView(pool){const topics=studyTopics.map(t=>({...t,references:topicReferences(t,pool,readingSources)})).filter(t=>t.references.length);const allowed=new Set(topics.flatMap(t=>t.references.map(r=>r.law+':'+r.article)));const selected=allowed.has(state.guideReference)&&readingSources[state.guideReference];return '<section class="panel"><h3>Estudar por tema e localizar artigos</h3><p>Escolhe um tema e lê o preceito. Nas lições, aplica a regra; em Artigos, treina recordação sem opções. Os pontos abaixo orientam a leitura e não esgotam o tema.</p>'+topics.map(t=>'<details><summary>'+escapeHTML(t.title)+'</summary>'+t.references.map(r=>'<button class="btn" data-guide-reference="'+r.law+':'+r.article+'">'+escapeHTML(legislation.find(l=>l.id===r.law)?.short||r.law)+' · '+escapeHTML(r.source.article)+' · '+escapeHTML(r.source.title)+'</button>').join('')+'</details>').join('')+(selected?'<article class="panel"><h3>'+escapeHTML(selected.article)+' · '+escapeHTML(selected.title)+'</h3><div class="reading-text">'+escapeHTML(selected.text)+'</div>'+questionSource(selected)+'<p>Depois de ler, fecha o texto e tenta recordar o artigo e explicar a regra antes de continuar o percurso.</p></article>':'')+'</section>';}
function examResearchView(){return '<section class="panel"><h3>Provas públicas usadas como referência</h3><p>Formatos e temas observados em fontes portuguesas. O banco contém perguntas próprias, com referência à legislação atual; não reproduz as provas históricas. O guia Concurso Público PT fornecido pelo utilizador ajudou a organizar temas e artigos. A descrição de SIADAP anterior a2025 exige atualização.</p>'+historicalExams.map(x=>'<details><summary>'+escapeHTML(x.entity)+' · '+x.year+'</summary><p>'+escapeHTML(x.role)+'</p><p>'+escapeHTML(x.structure)+'</p><p>'+escapeHTML(x.legalNote)+'</p><a href="'+escapeHTML(x.source)+'" target="_blank" rel="noopener">Consultar prova ou aviso oficial</a>'+(x.answerKey?' · <a href="'+escapeHTML(x.answerKey)+'" target="_blank" rel="noopener">Grelha histórica do júri</a>':'')+'</details>').join('')+'</section>';}
