import {testNotification,startReminders,shortcutGuide} from './notifications.js';
import {metrics,streak} from './analytics.js';
import {exportBackup,importBackup,downloadBackup} from './backup.js';
import {saveResponse} from './db.js';
import {getKV,setKV,allReviews,putReview,addAnswer,allAnswers,allCompetitions,putCompetition} from './db.js';
import {questions} from './data/questions.js';
import {legislation} from './data/legislation.js';
import {nextReview,buildSession,daysUntil,competitionPlan} from './engine.js';

const app=document.querySelector('#app');
const state={view:'home',profile:{region:'Madeira',area:'Recursos Humanos'},reviews:[],answers:[],competitions:[],session:[],index:0,answered:false,selected:null,onboarded:false,reminder:{enabled:false,time:'19:00'}};
const nav=[['home','⌂','Hoje'],['study','◉','Estudar'],['progress','▥','Progresso'],['laws','§','Leis'],['competitions','◎','Concursos'],['settings','⚙','Definições']];

async function init(){
 state.onboarded=Boolean(await getKV('onboarded'));state.reminder=(await getKV('reminder'))||state.reminder;
 state.profile=(await getKV('profile'))||state.profile; await setKV('profile',state.profile);
 state.reviews=await allReviews(); state.answers=await allAnswers(); state.competitions=await allCompetitions();
 if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js').catch(e=>console.error(e)); render();
}
function activeCompetition(){return state.competitions.find(c=>c.active)}
function calcAccuracy(){return state.answers.length?Math.round(state.answers.filter(a=>a.correct).length/state.answers.length*100):0}
function todaySession(){const c=activeCompetition();return buildSession(questions,state.reviews,state.profile.region,c?competitionPlan(c,questions,state.answers,state.profile.region).daily:12,c?.legislationIds||null,state.answers,c?.weights||{},state.profile.area)}
function startStudy(){state.session=todaySession();state.index=0;state.answered=false;state.selected=null;state.view='study';render()}
function navigate(v){if(v==='study')return startStudy();state.view=v;render()}
function shell(content){return `<div class="shell"><div class="brand"><img src="./icons/avatar.svg" alt="" width="44" height="44"><span>CONCURSO <b>STUDY</b></span><small>V0.2</small></div>${!state.onboarded?onboarding():''}${content}</div>${state.view!=='study'?bottomNav():''}`}
function bottomNav(){return `<nav class="bottom">${nav.map(([id,ico,label])=>`<button class="nav ${state.view===id?'active':''}" data-nav="${id}"><span class="ico">${ico}</span><span class="label">${label}</span></button>`).join('')}</nav>`}
function top(eyebrow,title){return `<header class="top"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1></div><span class="chip">${new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'short'}).format(new Date())}</span></header>`}
function home(){const s=todaySession(),acc=calcAccuracy(),due=state.reviews.filter(r=>new Date(r.dueAt)<=new Date()).length,c=activeCompetition();return shell(`${top(`${escapeHTML(state.profile.area)} · ${escapeHTML(state.profile.region)}`,'Hoje')}
 <section class="hero"><img class="mascot" src="./icons/avatar.svg" alt="Guardião do conhecimento" width="130" height="130"><div><p class="eyebrow" style="color:#bbb">Sessão diária</p><h2>${s.length} perguntas</h2><p>Revisão · pontos fracos · matéria nova</p></div><button class="btn btn-light" id="start">Começar →</button></section>
 <div class="stats"><div class="stat"><strong>${streak(state.answers)} ${streak(state.answers)===1?'dia':'dias'}</strong><span>dias consecutivos</span></div><div class="stat"><strong>${due}</strong><span>revisões</span></div><div class="stat"><strong>${state.answers.length?acc+'%':'sem dados'}</strong><span>acerto</span></div></div>
 ${c?`<div class="panel"><p class="eyebrow">Concurso ativo</p><h3>${escapeHTML(c.title)}</h3><p class="muted">${escapeHTML(c.entity)} · ${daysUntil(c.examDate)} dias até à prova</p></div>`:''}
 <div class="section-title"><p class="eyebrow">Mapa de domínio</p><h3>Matérias principais</h3></div>
 ${metricRows('law')}<p class="muted">${questions.filter(q=>!q.suspended).length} perguntas ativas · ${questions.filter(q=>q.suspended).length} suspensas para revisão da fonte.</p>`)}
function study(){const q=state.session[state.index];if(!q)return shell(`<div class="empty"><h2>Sem mais perguntas disponíveis nesta sessão.</h2><button class="btn btn-dark" data-nav="home">Voltar</button></div>`);const law=legislation.find(l=>l.id===q.law);return shell(`<div class="quiz-top"><button class="btn btn-ghost" data-nav="home">Fechar</button><div class="meter"><span style="width:${((state.index+1)/state.session.length)*100}%"></span></div><span class="muted">${state.index+1}/${state.session.length}</span></div>
 <section class="quiz"><p class="eyebrow">${law?.short||''} · nível ${q.difficulty}</p><h2>${q.prompt}</h2><div class="options">${q.options.map((o,i)=>{let cls='option';if(state.answered){if(i===q.correct)cls+=' correct';else if(i===state.selected)cls+=' wrong'}return `<button class="${cls}" data-answer="${i}"><b>${String.fromCharCode(65+i)}</b>${o}</button>`}).join('')}</div>
 ${state.answered?`<div class="explain"><strong>Explicação</strong><p class="feedback">${state.selected===q.correct?'Resposta correta':'Resposta incorreta'}</p><img class="feedback-avatar" src="./icons/avatar.svg" width="64" height="64" alt="Guardião do conhecimento"><p>${q.explanation}</p>${questionSource(q)}<button class="btn btn-dark" id="next">Continuar →</button></div>`:''}</section>`)}
function metricRows(dimension,pool=questions){return metrics(pool.filter(q=>!q.suspended),state.answers,dimension).map(g=>`<div class="panel"><strong>${escapeHTML(legislation.find(l=>l.id===g.key)?.short||g.key)}</strong><div class="coverage" aria-label="Cobertura ${g.coverage}%"><span style="width:${g.coverage}%"></span></div><p>${g.seen}/${g.total} perguntas vistas · ${g.attempts} ${g.attempts===1?'resposta':'respostas'} · acerto ${g.accuracy===null?'sem dados':g.accuracy+'%'} · domínio recente ${g.mastery===null?'sem dados':g.mastery+'%'}</p></div>`).join('')}
function progress(){return shell(top('Respostas registadas','Progresso')+'<p>Domínio recente: acerto ponderado com meia-vida de 30 dias. Cobertura: perguntas distintas vistas. Não equivale a domínio jurídico validado.</p>'+['law','topic','subtopic','difficulty'].map((d,i)=>'<h2>'+['Diploma','Tema','Subtema','Dificuldade'][i]+'</h2>'+metricRows(d)).join(''))}
function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function laws(){return shell(`${top('Base jurídica','Legislação')}<div class="grid">${legislation.map(l=>`<div class="panel law"><p class="eyebrow">${l.region}</p><h3>${l.short}</h3><div>${l.title}</div><small>${l.diploma}</small><div class="status">${lawStatus(l)}</div></div>`).join('')}</div>`)}
function competitions(){const items=state.competitions.map(c=>`<div class="panel"><p class="eyebrow">${c.active?'Ativo':'Arquivado'}</p><h3>${c.title}</h3><p>${c.entity}</p>${competitionSummary(c)}<button class="btn" data-activate="${escapeHTML(c.id)}">${c.active?'Arquivar':'Ativar'}</button></div>`).join('');return shell(`${top('Preparação específica','Concursos')}<div class="panel"><h3>Adicionar concurso</h3><form class="form" id="competitionForm"><label>Cargo / vaga</label><input name="title" required placeholder="Técnico Superior — RH"/><label>Entidade</label><input name="entity" required placeholder="Direção Regional de Educação"/><label>Data da prova</label><input name="examDate" required type="date"/><label>Legislação (seleciona pelo menos uma)</label><select name="laws" multiple size="6">${legislation.map(l=>`<option value="${l.id}">${l.short} — ${l.title}</option>`).join('')}</select><label>Pesos por diploma (1–10)</label>${legislation.map(l=>`<label>${l.short}<input type="number" min="1" max="10" value="1" name="weight-${l.id}"></label>`).join('')}<button class="btn btn-dark" style="margin-top:14px">Guardar concurso</button></form></div>${items}`)}
function settings(){return shell(`${top('Aplicação','Definições')}<div class="panel"><h3>Perfil</h3><form class="form" id="profileForm"><label>Região</label><select name="region"><option ${state.profile.region==='Madeira'?'selected':''}>Madeira</option><option ${state.profile.region==='Continente'?'selected':''}>Continente</option><option ${state.profile.region==='Açores'?'selected':''}>Açores</option></select><label>Área</label><select name="area"><option ${state.profile.area==='Recursos Humanos'?'selected':''}>Recursos Humanos</option>${['Gestão Financeira','Administração','Educação','Jurídico'].map(area=>`<option ${state.profile.area===area?'selected':''}>${area}</option>`).join('')}</select><button class="btn btn-dark" style="margin-top:14px">Guardar</button></form></div><div class="panel"><h3>Dados locais</h3><p class="muted">O backup inclui perfil, respostas, revisões, concursos e todas as chaves locais. Importar substitui os dados atuais.</p><button class="btn" id="exportBackup">Exportar backup</button><label>Importar JSON<input type="file" id="importBackup" accept="application/json,.json"></label></div>${reminderPanel()}`)}
function render(){app.innerHTML=state.view==='home'?home():state.view==='study'?study():state.view==='progress'?progress():state.view==='laws'?laws():state.view==='competitions'?competitions():settings();bind()}
function bind(){
 document.querySelector('#finishOnboarding')?.addEventListener('click',async()=>{await setKV('onboarded',true);state.onboarded=true;render()});
 document.querySelector('#testNotification')?.addEventListener('click',()=>testNotification().catch(e=>alert(e.message)));
 document.querySelector('#reminderForm')?.addEventListener('submit',async e=>{e.preventDefault();state.reminder={enabled:e.target.elements.enabled.checked,time:e.target.elements.time.value};await setKV('reminder',state.reminder);render()});

 document.querySelector('#exportBackup')?.addEventListener('click',async()=>{try{downloadBackup(await exportBackup())}catch(e){alert(e.message)}});
 document.querySelector('#importBackup')?.addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>50*1024*1024)throw Error('Limite: 50 MB.');const b=JSON.parse(await file.text());const {validateBackup}=await import('./backup.js');validateBackup(b);if(!confirm('Substituir todos os dados locais pelo backup? Será descarregada uma cópia dos dados atuais.'))return;downloadBackup(await exportBackup());await importBackup(b);await init();}catch(err){alert('Não foi possível importar: '+err.message)}});
 document.querySelectorAll('[data-activate]').forEach(b=>b.onclick=async()=>{const target=state.competitions.find(c=>c.id===b.dataset.activate),active=!target.active;for(const c of state.competitions){c.active=c.id===target.id&&active;await putCompetition(c)}render()});
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));document.querySelector('#start')?.addEventListener('click',startStudy);document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.answer)));document.querySelector('#next')?.addEventListener('click',()=>{state.index++;state.answered=false;state.selected=null;render()});
 document.querySelector('#profileForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);state.profile={region:f.get('region'),area:f.get('area')};await setKV('profile',state.profile);render()});
 document.querySelector('#competitionForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const selected=[...e.target.elements.laws.selectedOptions].map(o=>o.value);if(!selected.length){alert('Seleciona pelo menos um diploma.');return}const weights=Object.fromEntries(selected.map(id=>[id,Number(f.get('weight-'+id))||1]));for(const c of state.competitions){if(c.active){c.active=false;await putCompetition(c)}}const c={id:crypto.randomUUID(),title:f.get('title'),entity:f.get('entity'),examDate:f.get('examDate'),region:state.profile.region,legislationIds:selected,weights,active:true,createdAt:new Date().toISOString()};await putCompetition(c);state.competitions=await allCompetitions();render()});}
function competitionSummary(c){const p=competitionPlan(c,questions,state.answers,state.profile.region);return '<p>'+ (p.days===null?'Data inválida':p.days<0?'Prova passada':p.days===0?'Prova hoje':p.days+' dias até à prova')+' · '+p.total+' perguntas disponíveis</p><p>Plano: '+p.daily+' perguntas/dia; revisão, pontos fracos e matéria nova. A sessão pode ser menor devido ao banco e ao intervalo de repetição.</p>'+metricRows('law',questions.filter(q=>c.legislationIds?.includes(q.law)&&(q.region==='Nacional'||q.region===(c.region||state.profile.region))))}
async function answer(i){if(state.answered)return;state.answered=true;const q=state.session[state.index],correct=i===q.correct;try{await saveResponse({questionId:q.id,correct,selected:i,competitionId:activeCompetition()?.id||null,answeredAt:new Date().toISOString()},nextReview(state.reviews.find(r=>r.questionId===q.id),correct,q.id));state.selected=i;state.reviews=await allReviews();state.answers=await allAnswers();render()}catch(e){state.answered=false;alert('Resposta não guardada: '+e.message)}}
startReminders(()=>{const banner=document.createElement('div');banner.className='reminder-banner';banner.setAttribute('role','status');banner.textContent='Hora de estudar. Abre Estudar para iniciar a sessão diária.';document.querySelector('#app').prepend(banner)});
init().catch(e=>{app.textContent='Não foi possível abrir os dados locais: '+e.message});



function onboarding(){return '<section class="onboarding"><img src="./icons/avatar.svg" alt="" width="90" height="90"><div><p class="eyebrow">Preparação diária</p><h2>Estuda com método.</h2><p>Escolhe a região, responde à sessão e acompanha o progresso. Os dados ficam neste dispositivo: exporta um backup regularmente.</p><button class="btn btn-dark" id="finishOnboarding">Começar</button></div></section>'}
function safeSource(url){try{const u=new URL(url);return u.protocol==='https:'&&['diariodarepublica.pt','www.parlamento.pt','eur-lex.europa.eu','joram.madeira.gov.pt'].includes(u.hostname)?escapeHTML(u.href):null}catch{return null}}
function questionSource(q){const url=safeSource(q.officialSource);return '<div class="legal">'+escapeHTML(q.article)+' · '+escapeHTML(q.legalVersion||'Versão por confirmar')+'<br>Conferência do texto: '+escapeHTML(q.lastValidated||'não realizada')+(url?' · <a href="'+url+'" target="_blank" rel="noopener">Consultar fonte oficial</a>':'')+'</div>'}
function lawStatus(l){const items=questions.filter(q=>q.law===l.id&&!q.suspended),sourced=items.filter(q=>q.officialSource).length;const source=items.find(q=>safeSource(q.officialSource));return items.length+' perguntas ativas · '+sourced+' com fonte e artigo'+(source?' · <a href="'+safeSource(source.officialSource)+'" target="_blank" rel="noopener">Fonte oficial</a>':' · aguarda validação da legislação aplicável')}
function reminderPanel(){return '<section class="panel"><h3>Lembretes</h3><p>Enquanto a aplicação estiver aberta, mostra um lembrete à hora escolhida. Com a app fechada, configura a automação nos Atalhos.</p><form class="form" id="reminderForm"><label><input name="enabled" type="checkbox" '+(state.reminder.enabled?'checked':'')+'> Lembrete na aplicação</label><label>Hora local<input name="time" type="time" required value="'+escapeHTML(state.reminder.time)+'"></label><button class="btn btn-dark">Guardar lembrete</button></form><button class="btn" id="testNotification">Testar notificação do dispositivo</button><details><summary>Configurar Atalhos no iPhone</summary>'+shortcutGuide()+'<p>Endereço da app: <code>'+escapeHTML(typeof location==='undefined'?'endereço do GitHub Pages':location.href.split('#')[0])+'</code></p><p>No iPhone, o teste de notificação pode exigir a app adicionada ao ecrã principal e permissão do sistema.</p></details></section>'}

