import {getKV,setKV,allReviews,putReview,addAnswer,allAnswers,allCompetitions,putCompetition} from './db.js';
import {questions} from './data/questions.js';
import {legislation} from './data/legislation.js';
import {nextReview,buildSession,daysUntil} from './engine.js';

const app=document.querySelector('#app');
const state={view:'home',profile:{region:'Madeira',area:'Recursos Humanos'},reviews:[],answers:[],competitions:[],session:[],index:0,answered:false,selected:null};
const nav=[['home','⌂','Hoje'],['study','◉','Estudar'],['progress','▥','Progresso'],['laws','§','Leis'],['competitions','◎','Concursos'],['settings','⚙','Definições']];

async function init(){
 state.profile=(await getKV('profile'))||state.profile; await setKV('profile',state.profile);
 state.reviews=await allReviews(); state.answers=await allAnswers(); state.competitions=await allCompetitions();
 if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js'); render();
}
function activeCompetition(){return state.competitions.find(c=>c.active)}
function calcAccuracy(){return state.answers.length?Math.round(state.answers.filter(a=>a.correct).length/state.answers.length*100):0}
function todaySession(){const c=activeCompetition();return buildSession(questions,state.reviews,state.profile.region,12,c?.legislationIds||null)}
function startStudy(){state.session=todaySession();state.index=0;state.answered=false;state.selected=null;state.view='study';render()}
function navigate(v){if(v==='study')return startStudy();state.view=v;render()}
function shell(content){return `<div class="shell">${content}</div>${state.view!=='study'?bottomNav():''}`}
function bottomNav(){return `<nav class="bottom">${nav.map(([id,ico,label])=>`<button class="nav ${state.view===id?'active':''}" data-nav="${id}"><span class="ico">${ico}</span><span class="label">${label}</span></button>`).join('')}</nav>`}
function top(eyebrow,title){return `<header class="top"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1></div><span class="chip">${new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'short'}).format(new Date())}</span></header>`}
function home(){const s=todaySession(),acc=calcAccuracy(),due=state.reviews.filter(r=>new Date(r.dueAt)<=new Date()).length,c=activeCompetition();return shell(`${top(`${state.profile.area} · ${state.profile.region}`,'Hoje')}
 <section class="hero"><div><p class="eyebrow" style="color:#bbb">Sessão diária</p><h2>${s.length||6} perguntas</h2><p>~8 minutos</p></div><button class="btn btn-light" id="start">Começar →</button></section>
 <div class="stats"><div class="stat"><strong>${Math.max(1,Math.min(30,state.answers.length?4:1))} dias</strong><span>streak</span></div><div class="stat"><strong>${due}</strong><span>revisões</span></div><div class="stat"><strong>${acc}%</strong><span>acerto</span></div></div>
 ${c?`<div class="panel"><p class="eyebrow">Concurso ativo</p><h3>${c.title}</h3><p class="muted">${c.entity} · ${daysUntil(c.examDate)} dias até à prova</p></div>`:''}
 <div class="section-title"><p class="eyebrow">Mapa de domínio</p><h3>Matérias principais</h3></div>
 ${[['CPA',82],['LTFP',74],['SIADAP-RAM',63],['Procedimento concursal',79],['RGPD',71]].map(([n,v])=>`<div class="row"><div><strong>${n}</strong><span class="muted">revisão adaptativa</span></div><div class="bar"><span style="width:${v}%"></span></div></div>`).join('')}`)}
function study(){if(!state.session.length)state.session=todaySession();const q=state.session[state.index];if(!q)return shell(`<div class="empty"><h2>Sessão concluída.</h2><button class="btn btn-dark" data-nav="home">Voltar</button></div>`);const law=legislation.find(l=>l.id===q.law);return shell(`<div class="quiz-top"><button class="btn btn-ghost" data-nav="home">Fechar</button><div class="meter"><span style="width:${((state.index+1)/state.session.length)*100}%"></span></div><span class="muted">${state.index+1}/${state.session.length}</span></div>
 <section class="quiz"><p class="eyebrow">${law?.short||''} · nível ${q.difficulty}</p><h2>${q.prompt}</h2><div class="options">${q.options.map((o,i)=>{let cls='option';if(state.answered){if(i===q.correct)cls+=' correct';else if(i===state.selected)cls+=' wrong'}return `<button class="${cls}" data-answer="${i}"><b>${String.fromCharCode(65+i)}</b>${o}</button>`}).join('')}</div>
 ${state.answered?`<div class="explain"><strong>Explicação</strong><p>${q.explanation}</p>${q.article?`<div class="legal">${q.article}</div>`:''}<button class="btn btn-dark" id="next">Continuar →</button></div>`:''}</section>`)}
function progress(){const acc=calcAccuracy();return shell(`${top('Evolução','Progresso')}<div class="hero"><div><p class="eyebrow" style="color:#bbb">Acerto global</p><h2>${acc}%</h2><p>${state.answers.length} respostas registadas</p></div></div><div class="panel"><h3>Estrutura pronta</h3><p class="muted">A próxima versão calcula domínio por diploma, tema, dificuldade, erro e tempo de resposta.</p></div>`)}
function laws(){return shell(`${top('Base jurídica','Legislação')}<div class="grid">${legislation.map(l=>`<div class="panel law"><p class="eyebrow">${l.region}</p><h3>${l.short}</h3><div>${l.title}</div><small>${l.diploma}</small><div class="status">Verificado em ${l.verified} · ${l.source}</div></div>`).join('')}</div>`)}
function competitions(){const items=state.competitions.map(c=>`<div class="panel"><p class="eyebrow">${c.active?'Ativo':'Arquivado'}</p><h3>${c.title}</h3><p>${c.entity}</p><span class="badge">${daysUntil(c.examDate)} dias</span></div>`).join('');return shell(`${top('Preparação específica','Concursos')}<div class="panel"><h3>Adicionar concurso</h3><form class="form" id="competitionForm"><label>Cargo / vaga</label><input name="title" required placeholder="Técnico Superior — RH"/><label>Entidade</label><input name="entity" required placeholder="Direção Regional de Educação"/><label>Data da prova</label><input name="examDate" required type="date"/><label>Legislação</label><select name="laws" multiple size="6">${legislation.map(l=>`<option value="${l.id}">${l.short} — ${l.title}</option>`).join('')}</select><button class="btn btn-dark" style="margin-top:14px">Guardar concurso</button></form></div>${items}`)}
function settings(){return shell(`${top('Aplicação','Definições')}<div class="panel"><h3>Perfil</h3><form class="form" id="profileForm"><label>Região</label><select name="region"><option ${state.profile.region==='Madeira'?'selected':''}>Madeira</option><option ${state.profile.region==='Continente'?'selected':''}>Continente</option><option ${state.profile.region==='Açores'?'selected':''}>Açores</option></select><label>Área</label><select name="area"><option ${state.profile.area==='Recursos Humanos'?'selected':''}>Recursos Humanos</option><option>Gestão Financeira</option><option>Administração</option><option>Educação</option><option>Jurídico</option></select><button class="btn btn-dark" style="margin-top:14px">Guardar</button></form></div><div class="panel"><h3>Dados locais</h3><p class="muted">O progresso fica guardado no iPhone através de IndexedDB. Backup/exportação entra na próxima versão.</p></div>`)}
function render(){app.innerHTML=state.view==='home'?home():state.view==='study'?study():state.view==='progress'?progress():state.view==='laws'?laws():state.view==='competitions'?competitions():settings();bind()}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));document.querySelector('#start')?.addEventListener('click',startStudy);document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.answer)));document.querySelector('#next')?.addEventListener('click',()=>{state.index++;state.answered=false;state.selected=null;render()});
 document.querySelector('#profileForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);state.profile={region:f.get('region'),area:f.get('area')};await setKV('profile',state.profile);render()});
 document.querySelector('#competitionForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const selected=[...e.target.elements.laws.selectedOptions].map(o=>o.value);for(const c of state.competitions){if(c.active){c.active=false;await putCompetition(c)}}const c={id:crypto.randomUUID(),title:f.get('title'),entity:f.get('entity'),examDate:f.get('examDate'),region:state.profile.region,legislationIds:selected,active:true,createdAt:new Date().toISOString()};await putCompetition(c);state.competitions=await allCompetitions();render()});}
async function answer(i){if(state.answered)return;const q=state.session[state.index],correct=i===q.correct;state.selected=i;state.answered=true;await addAnswer({questionId:q.id,correct,answeredAt:new Date().toISOString()});const current=state.reviews.find(r=>r.questionId===q.id);await putReview(nextReview(current,correct,q.id));state.reviews=await allReviews();state.answers=await allAnswers();render()}
init();
