import {questions} from './data/questions.js';
import {legislation} from './data/legislation.js';
import {programmes,programmeReferences} from './data/programmes.js';
const el=document.querySelector('#coverage');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let inventory,circulars,law='ltfp',page=0,onlyGaps=false;
const active=questions.filter(q=>!q.suspended),byArticle=new Map();
for(const q of active){if(!q.articleNumber)continue;const key=q.law+':'+q.articleNumber;if(!byArticle.has(key))byArticle.set(key,[]);byArticle.get(key).push(q)}
function referenceLabel(a){const prefix={annex:'Anexo ',section:'Secção ',approval:'Decreto de aprovação, art. ',point:'Ponto '}[a.referenceKind]||(a.law.startsWith('circ')?'Ponto ':'Art. ');return prefix+esc(a.article);}
function render(){
 const items=inventory.articles.filter(a=>a.law===law),rows=items.filter(a=>!onlyGaps||!byArticle.has(a.law+':'+a.article));
 page=Math.min(page,Math.max(0,Math.ceil(rows.length/40)-1));
 const covered=items.filter(a=>byArticle.has(a.law+':'+a.article)).length,qs=active.filter(q=>q.law===law),families=new Set(qs.map(q=>q.familyId||q.id)).size;
 el.innerHTML='<section class="panel"><label>Diploma<select id="law">'+legislation.filter(l=>inventory.articles.some(a=>a.law===l.id)).map(l=>'<option value="'+l.id+'" '+(law===l.id?'selected':'')+'>'+esc(l.short)+'</option>').join('')+'</select></label><label><input id="gaps" type="checkbox" '+(onlyGaps?'checked':'')+'> Mostrar apenas artigos sem perguntas ativas</label><h2>'+esc(legislation.find(l=>l.id===law)?.title)+'</h2><p>'+items.length+' artigos inventariados · '+covered+' com perguntas · '+qs.length+' perguntas de escolha múltipla · '+families+' grupos de treino.</p><p>Os grupos distinguem regras de variantes. As perguntas podem trabalhar apenas parte de um artigo. Extração: '+esc(inventory.date)+'.</p></section>'+rows.slice(page*40,page*40+40).map(a=>{
  const q=byArticle.get(a.law+':'+a.article)||[];
  return '<details class="panel"><summary>'+referenceLabel(a)+' · '+esc(a.title)+' · '+q.length+' perguntas'+(a.revoked?' · texto revogado':'')+'</summary><p>'+esc(a.version)+'</p><a href="'+esc(a.source)+'" target="_blank" rel="noopener">Fonte oficial</a>'+(a.legalContext?'<aside class="legal-context"><strong>Aplicação da norma</strong><p>'+esc(a.legalContext)+'</p>'+(a.relatedSources||[]).map(s=>'<a href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.title)+'</a>').join(' · ')+'</aside>':'')+(q.length?'<p>Regras e situações trabalhadas: '+[...new Set(q.map(x=>x.topic))].map(esc).join(' · ')+'.</p><p>'+a.documentaryReviewedQuestions+' perguntas com conferência documental; '+(a.status==='COMPLETE'?'inventário de conceitos e correspondência expressa concluídos.':'consultar o estado e fundamento abaixo.')+'</p>':'<p>Sem perguntas ativas. O texto abaixo serve de referência.</p>')+'<p><strong>'+esc(a.status==='COMPLETE'?'Conferência documental concluída':a.status==='REVOKED_WITH_TRANSITION_REVIEW'?'Revogado — transição conferida':a.status==='EXCLUDED_WITH_REASON'?'Excluído com fundamento':'Revisão pendente')+'</strong></p>'+(a.exclusionReason?'<p>'+esc(a.exclusionReason)+' '+esc(a.scopeReview)+'</p>':'')+(a.transitionAnalysis?'<p>'+esc(a.transitionAnalysis)+'</p>'+a.transitionSources.map(s=>'<a href="'+esc(typeof s==='string'?'':s.url)+'" target="_blank" rel="noopener">'+esc(typeof s==='string'?s:s.title)+'</a>').join(' · '):'')+(a.concepts?.length?'<details><summary>'+a.concepts.length+' conceitos conferidos</summary><ul>'+a.concepts.map(c=>'<li>'+esc(c.objective)+'</li>').join('')+'</ul></details>':'')+'<p>'+a.norms.length+' segmentos do texto de referência.</p>'+a.norms.map(n=>'<details><summary>'+esc(n.ref)+'</summary><p>'+esc(n.text)+'</p></details>').join('')+'</details>';
 }).join('')+'<section class="panel"><button class="btn" id="prev" '+(page===0?'disabled':'')+'>Anterior</button> Página '+(page+1)+'/'+Math.max(1,Math.ceil(rows.length/40))+' <button class="btn" id="next" '+((page+1)*40>=rows.length?'disabled':'')+'>Seguinte</button></section>'+limitations()+references();
 document.querySelector('#law').onchange=e=>{law=e.target.value;page=0;render()};
 document.querySelector('#gaps').onchange=e=>{onlyGaps=e.target.checked;page=0;render()};
 document.querySelector('#prev').onclick=()=>{page--;render();window.scrollTo(0,0)};
 document.querySelector('#next').onclick=()=>{page++;render();window.scrollTo(0,0)};
}
function limitations(){return '<section class="panel"><h2>'+ (inventory.status==='COMPLETE'?'Cobertura documental do inventário concluída':'Revisão em curso')+'</h2><p>'+esc(inventory.definition)+'</p><p>'+inventory.summary.articlesWithCompletedCoverage+' entradas com conceitos cobertos; disposições revogadas com análise transitória; exclusões fundamentadas. Conferência em '+esc(inventory.reviewDate)+', legislação de referência '+esc(inventory.date)+'.</p><p>O estado da matriz mede o banco. As percentagens pessoais medem as respostas do utilizador e não certificam domínio de toda a legislação.</p><h3>Condições e limites de aplicação</h3><ul>'+(inventory.operationalLimits||[]).map(s=>'<li>'+esc(s)+'</li>').join('')+'<li>Conferência documental pelo agente, sem certificação jurídica independente. Instrumentos coletivos e regulamentos do empregador exigem consulta própria.</li><li>Os programas DRE/Funchal usam textos atuais por escolha do utilizador; o júri pode exigir a versão da data do aviso.</li><li>Orçamento/execução 2026; Conta de 2025 histórica; preparação 2027 não equivale a orçamento aprovado.</li></ul><h3>Referências históricas — circulares de 2025</h3>'+circulars.map(c=>'<p>'+esc(c.label)+'<br>'+c.attachments.map(a=>'<a href="'+esc(a.url)+'" target="_blank" rel="noopener">'+esc(a.label)+'</a>').join(' · ')+'</p>').join('')+'</section>'}
function references(){return '<section class="panel"><h2>Programas e fontes</h2>'+programmeReferences.map(r=>'<p><a href="'+esc(r.source)+'" target="_blank" rel="noopener">'+esc(r.entity)+' · '+esc(r.code)+'</a><br>'+esc(r.notes)+'</p>').join('')+programmes.slice(1).map(p=>'<p><strong>'+esc(p.title)+'</strong><br>'+esc(p.description)+'</p>').join('')+'</section>'}
Promise.all([fetch('./data/coverage.json').then(r=>{if(!r.ok)throw Error('Inventário indisponível');return r.json()}),fetch('./data/circulares-2025.json').then(r=>{if(!r.ok)throw Error('Catálogo indisponível');return r.json()})]).then(([i,c])=>{inventory=i;circulars=c;render()}).catch(e=>{el.textContent='Não foi possível carregar a matriz: '+e.message});
