import {questions} from './data/questions.js';
import {legislation} from './data/legislation.js';
import {programmes,programmeReferences} from './data/programmes.js';
const el=document.querySelector('#coverage');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let inventory,circulars,law='ltfp',page=0,onlyGaps=false;
const active=questions.filter(q=>!q.suspended),byArticle=new Map();for(const q of active){if(!q.articleNumber)continue;const key=q.law+':'+q.articleNumber;if(!byArticle.has(key))byArticle.set(key,[]);byArticle.get(key).push(q)}
function render(){
 const items=inventory.articles.filter(a=>a.law===law),rows=items.filter(a=>!onlyGaps||!byArticle.has(a.law+':'+a.article));
 page=Math.min(page,Math.max(0,Math.ceil(rows.length/40)-1));const covered=items.filter(a=>byArticle.has(a.law+':'+a.article)).length,qs=active.filter(q=>q.law===law),cases=qs.filter(q=>q.questionType!=='norma-lacuna').length;
 el.innerHTML='<section class="panel"><label>Diploma<select id="law">'+legislation.filter(l=>inventory.articles.some(a=>a.law===l.id)).map(l=>'<option value="'+l.id+'" '+(law===l.id?'selected':'')+'>'+esc(l.short)+'</option>').join('')+'</select></label><label><input id="gaps" type="checkbox" '+(onlyGaps?'checked':'')+'> Mostrar apenas artigos sem exercícios ativos</label><h2>'+esc(legislation.find(l=>l.id===law)?.title)+'</h2><p>'+items.length+' artigos extraídos · '+covered+' com exercício · '+qs.length+' perguntas: '+(qs.length-cases)+' de leitura literal e '+cases+' de conceito/aplicação.</p><p>Extração: '+esc(inventory.date)+'. Revogações, remissões, anexos técnicos, atos de aprovação e normas externas exigem consulta própria. Não foram convertidos em casos só por constarem do inventário.</p></section>'+rows.slice(page*40,page*40+40).map(a=>{const q=byArticle.get(a.law+':'+a.article)||[];return '<details class="panel"><summary>Art. '+esc(a.article)+' · '+esc(a.title)+' · '+q.length+' exercícios'+(a.revoked?' · texto revogado':'')+'</summary><p>'+esc(a.version)+'</p><a href="'+esc(a.source)+'" target="_blank" rel="noopener">Fonte oficial</a><p>'+a.norms.length+' segmentos extraídos. '+a.norms.filter(n=>n.questionIds.length).length+' com exercício literal; '+a.norms.filter(n=>n.status==='sem exercício').length+' sem exercício literal. Casos adicionais são contabilizados por artigo.</p>'+a.norms.map(n=>'<details><summary>'+esc(n.ref)+' · '+esc(n.status)+'</summary><p>'+esc(n.text)+'</p></details>').join('')+'</details>'}).join('')+'<section class="panel"><button class="btn" id="prev" '+(page===0?'disabled':'')+'>Anterior</button> Página '+(page+1)+'/'+Math.max(1,Math.ceil(rows.length/40))+' <button class="btn" id="next" '+((page+1)*40>=rows.length?'disabled':'')+'>Seguinte</button></section>'+limitations()+references();
 document.querySelector('#law').onchange=e=>{law=e.target.value;page=0;render()};document.querySelector('#gaps').onchange=e=>{onlyGaps=e.target.checked;page=0;render()};document.querySelector('#prev').onclick=()=>{page--;render();window.scrollTo(0,0)};document.querySelector('#next').onclick=()=>{page++;render();window.scrollTo(0,0)};
}
function limitations(){return '<section class="panel"><h2>Limites do levantamento</h2><ul><li>O inventário abrange os articulados extraídos de 26 diplomas. Não é um mapa semanticamente validado de todos os conceitos jurídicos.</li><li>O núcleo de leitura usa lacunas em excertos, níveis 1–2. Os casos e conceitos existentes usam níveis 1–5. A maioria das novas perguntas não é um caso complexo.</li><li>Os programas Funchal 2024 e DRE 2026 selecionam matérias. Não reconstituem automaticamente a versão jurídica da data da prova ou do aviso.</li><li>O aviso DRE cita o DRR 5/2024/M, revogado pelo DRR 15/2024/M. Referência excluída do treino atual e pendente de esclarecimento pelo júri.</li><li>ORAM e execução de 2025 só aparecem no programa DRE. Não são apresentados como orçamento de 2026.</li><li>Circulares DROT 2025: sete documentos e uma errata identificados. Os PDFs contêm texto de reconhecimento ótico com erros; não foram convertidos automaticamente em perguntas jurídicas. A análise e os exercícios de aplicação de cada ponto continuam pendentes.</li><li>Não se certifica a cobertura de jurisprudência, instrumentos coletivos, tabelas remuneratórias anuais, proteção social, ajudas de custo ou regulamentos específicos de outras entidades.</li></ul><h3>Circulares de 2025 identificadas</h3>'+circulars.map(c=>'<p>'+esc(c.label)+'<br>'+c.attachments.map(a=>'<a href="'+esc(a.url)+'" target="_blank" rel="noopener">'+esc(a.label)+'</a>').join(' · ')+'</p>').join('')+'</section>'}
function references(){return '<section class="panel"><h2>Programas e fontes</h2>'+programmeReferences.map(r=>'<p><a href="'+esc(r.source)+'" target="_blank" rel="noopener">'+esc(r.entity)+' · '+esc(r.code)+'</a><br>'+esc(r.notes)+'</p>').join('')+programmes.slice(1).map(p=>'<p><strong>'+esc(p.title)+'</strong><br>'+esc(p.description)+'</p>').join('')+'</section>'}
Promise.all([fetch('./data/coverage.json').then(r=>{if(!r.ok)throw Error('Inventário indisponível');return r.json()}),fetch('./data/circulares-2025.json').then(r=>{if(!r.ok)throw Error('Catálogo indisponível');return r.json()})]).then(([i,c])=>{inventory=i;circulars=c;render()}).catch(e=>{el.textContent='Não foi possível carregar a matriz: '+e.message});
