import {metrics} from './analytics.js';
export function nextReview(current,correct,questionId,now=Date.now()){let streak=correct?(current?.streak||0)+1:0;const ease=Math.max(1.4,Math.min(3,(current?.ease||2.3)+(correct?.08:-.2)));const intervalDays=correct?(streak===1?1:streak===2?3:Math.max(4,Math.round((current?.intervalDays||1)*ease))):.25;return {questionId,streak,ease,intervalDays,lastAnsweredAt:new Date(now).toISOString(),lastResult:correct?'correct':'wrong',dueAt:new Date(now+intervalDays*86400000).toISOString()}}
export function administrationScope(profile){return profile.administrationScope||(profile.region==='Madeira'?'regional-ram':'central')}
export function eligible(questions,region,lawFilter,area,scope=null,programme=null){return questions.filter(q=>!q.suspended&&(q.region==='Nacional'||q.region===region)&&(!lawFilter?.length||lawFilter.includes(q.law))&&(!area||q.professionalArea==='Geral'||q.professionalArea===area)&&(!scope||!q.administrationScopes||q.administrationScopes.includes(scope))&&(!q.programmeOnly||q.programmeOnly.includes(programme)))}
export function buildSession(questions,reviews,region='Madeira',limit=12,lawFilter=null,answers=[],weights={},area=null,now=Date.now(),scope=null,programme=null){
 const pool=eligible(questions,region,lawFilter,area,scope,programme), r=new Map(reviews.map(x=>[x.questionId,x])),last=new Map();for(const a of answers)last.set(a.questionId,Math.max(last.get(a.questionId)||0,new Date(a.answeredAt).getTime()||0));for(const x of reviews)if(x.lastAnsweredAt)last.set(x.questionId,Math.max(last.get(x.questionId)||0,new Date(x.lastAnsweredAt).getTime()||0));
 const available=pool.filter(q=>now-(last.get(q.id)||0)>=6*3600000);const topic=new Map(metrics(pool,answers,'topic',now).map(g=>[g.key,g.mastery??50]));const priority=q=>(100-(topic.get(q.topic)??50))*(Number(weights[q.law])||1);
 const due=available.filter(q=>r.has(q.id)&&new Date(r.get(q.id).dueAt).getTime()<=now).sort((a,b)=>new Date(r.get(a.id).dueAt)-new Date(r.get(b.id).dueAt)||priority(b)-priority(a));
 const weak=available.filter(q=>last.has(q.id)||r.has(q.id)).sort((a,b)=>priority(b)-priority(a)||(last.get(a.id)||0)-(last.get(b.id)||0));
 const day=Math.floor(now/86400000),hash=id=>{let h=day;for(const c of id)h=(Math.imul(h,31)+c.charCodeAt(0))>>>0;return h};
 const fresh=available.filter(q=>!last.has(q.id)&&!r.has(q.id)).sort((a,b)=>(Number(weights[b.law])||1)-(Number(weights[a.law])||1)||hash(a.id)-hash(b.id));
 // Interleave laws and reserve roughly one in four new questions for authored concepts/cases.
 const queues=new Map();for(const q of fresh){const kind=q.questionType==='norma-lacuna'?'norma':'caso',key=q.law+'|'+kind;if(!queues.has(key))queues.set(key,{law:q.law,kind,items:[]});queues.get(key).items.push(q)}
 const balanced=[],served=new Map();let count=0;while(balanced.length<Math.min(limit,fresh.length)){const choices=[...queues.values()].filter(x=>x.items.length),kind=count%4===0?'caso':'norma';choices.sort((a,b)=>Number(b.kind===kind)-Number(a.kind===kind)||(Number(weights[b.law])||1)-(Number(weights[a.law])||1)||(served.get(a.law)||0)-(served.get(b.law)||0)||hash(a.law)-hash(b.law));const queue=choices[0];balanced.push(queue.items.shift());served.set(queue.law,(served.get(queue.law)||0)+1);count++}
 const chosen=[],ids=new Set(),dueIds=new Set(due.map(q=>q.id));const take=(list,n)=>{for(const q of list){if(n<=0||chosen.length>=limit)break;if(!ids.has(q.id)){chosen.push(q);ids.add(q.id);n--}}};take(due,Math.round(limit*.5));take(weak.filter(q=>!dueIds.has(q.id)),Math.round(limit*.3));take(balanced,limit-chosen.length);take(due,limit);take(weak,limit);take(balanced,limit);return chosen;
}
export function daysUntil(date,now=new Date()){if(!/^\d{4}-\d{2}-\d{2}$/.test(date||''))return null;const [y,m,d]=date.split('-').map(Number);const target=Date.UTC(y,m-1,d);if(new Date(target).toISOString().slice(0,10)!==date)return null;return Math.round((target-Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()))/86400000)}
export function competitionPlan(c,questions,answers,region,now=new Date()){const pool=eligible(questions,c.region||region,c.legislationIds,c.area,c.administrationScope||((c.region||region)==='Madeira'?'regional-ram':'central'),c.programme),g=metrics(pool,answers,'law',now.getTime()),days=daysUntil(c.examDate,now);const unseen=g.reduce((s,x)=>s+x.total-x.seen,0);return {groups:g,days,total:pool.length,daily:days!==null&&days>=0?Math.min(40,Math.max(12,Math.ceil(unseen/Math.max(1,days)))):0};}

