import {examPresets,normalizeExamRules,selectExamQuestions,remainingExamSeconds,scoreExam,simulationSchedule} from './exam-mode.js';
import {getKV,setKV,saveExamResult} from './db.js';
import {nextReview,examEligible} from './engine.js';
import {readingSources} from './data/reading-sources.js';

export function examFormFields(escapeHTML,rules={}){
 const r=normalizeExamRules(rules),input=(name,label,value,min,max,step='1')=>'<label>'+label+'<input name="'+name+'" type="number" min="'+min+'" max="'+max+'" step="'+step+'" value="'+(value??'')+'"></label>';
 return '<details><summary>Regras da prova e treino do simulado</summary><p>Transcreve o aviso e a ata. Campos vazios significam regra por confirmar. O simulado apresenta escolhas únicas e pode incluir escrita.</p><label>Referência de formato<select name="examPreset">'+examPresets.map(p=>'<option value="'+p.id+'">'+escapeHTML(p.label)+'</option>').join('')+'</select></label><button class="btn" type="button" data-apply-exam-preset>Preencher regras desta referência</button>'+input('durationMinutes','Duração em minutos (vazio: treino sem limite)',r.durationMinutes,1,300)+'<label>Consulta permitida pelo aviso<select name="consultation">'+[['unknown','Por confirmar'],['forbidden','Sem consulta'],['permitted','Com consulta']].map(([v,t])=>'<option value="'+v+'" '+(r.consultation===v?'selected':'')+'>'+t+'</option>').join('')+'</select></label><label>Formato indicado pelo aviso<select name="officialFormat">'+[['unknown','Por confirmar'],['written','Escrita; tipos por confirmar'],['single-choice','Escolha única'],['mixed','Misto'],['multi-choice','Várias alternativas corretas'],['true-false','Verdadeiro/falso']].map(([v,t])=>'<option value="'+v+'" '+(r.officialFormat===v?'selected':'')+'>'+t+'</option>').join('')+'</select></label>'+input('questionCount','Escolhas únicas por simulado de treino',r.questionCount,1,60)+input('automaticPoints','Cotação da componente automática (0–20)',r.automaticPoints,1,20,'.01')+input('wrongPenalty','Penalização por erro como fração da cotação da pergunta (vazio: desconhecida)',r.wrongPenalty,0,1,'.01')+input('essayCount','Respostas de desenvolvimento no treino',r.essayCount,0,3)+input('essayLimitLines','Limite de linhas por resposta escrita (vazio: sem limite definido)',r.essayLimitLines,1,100)+'<label>Fonte do aviso ou ata<input name="examSource" type="url" value="'+escapeHTML(r.source)+'" placeholder="https://..."></label><label>Regras e limitações confirmadas<textarea name="examSourceNote">'+escapeHTML(r.sourceNote)+'</textarea></label><p id="examPresetNote"></p></details>';
}
export function readExamRules(form){const f=new FormData(form);return normalizeExamRules({...Object.fromEntries(['durationMinutes','consultation','officialFormat','questionCount','automaticPoints','wrongPenalty','essayCount','essayLimitLines'].map(k=>[k,f.get(k)])),source:f.get('examSource'),sourceNote:f.get('examSourceNote'),preset:f.get('examPreset')});}
export function examRulesSummary(c,escapeHTML){const r=normalizeExamRules(c.examRules),schedule=simulationSchedule(c);return '<section class="exam-rules"><p>'+ (r.durationMinutes?r.durationMinutes+' minutos':'Duração por confirmar')+' · '+({unknown:'Consulta por confirmar',permitted:'Com consulta',forbidden:'Sem consulta'}[r.consultation])+'</p><p>'+escapeHTML(r.sourceNote||'Confirma o formato, as cotações e a legislação de referência na ata do júri.')+'</p><p>Treino: '+r.questionCount+' escolhas únicas'+(r.essayCount?' e '+r.essayCount+(r.essayCount===1?' resposta escrita':' respostas escritas'):'')+'. '+(schedule.perWeek?'Plano sugerido: '+schedule.perWeek+(schedule.perWeek===1?' simulado por semana.':' simulados por semana.'):'Ajusta a data da prova para obter uma frequência sugerida.')+'</p><p>A nota automática avalia apenas este treino. Escrita e formatos com várias respostas ou verdadeiro/falso exigem treino e correção próprios.</p></section>';}
export function createExamController(api){
 let run=null,activeDraft=null,history=[],busy=false,timer=null,changing=false,changes=Promise.resolve();
 const e=api.escapeHTML;
 async function load(){history=(await getKV('examHistory'))||[];run=(await getKV('examDraft'))||null;activeDraft=run?.status==='running'?structuredClone(run):null;}
 async function persist(){await setKV('examDraft',run);activeDraft=structuredClone(run);}
 function stopTimer(){if(timer){clearInterval(timer);timer=null}}
 function startTimer(){stopTimer();if(run?.status!=='running'||!run.deadline)return;timer=setInterval(async()=>{if(api.currentView()!=='exam')return;const seconds=remainingExamSeconds(run),node=document.querySelector('#examTimer');if(node)node.textContent=clockText(seconds);if(seconds===0&&!busy&&!changing)await finish('time')},1000);}
 const clockText=s=>s===null?'Sem limite de tempo':Math.floor(s/60)+':'+String(s%60).padStart(2,'0');
 async function enter(c){await load();if(!run||run.status!=='running'){run={status:'setup',competition:structuredClone(c)};api.show();return}api.show();startTimer();if(remainingExamSeconds(run)===0)await finish('time');}
 async function start(){if(busy)return;busy=true;try{const pending=await getKV('examDraft');if(pending?.status==='running'){run=pending;activeDraft=structuredClone(pending);api.show();startTimer();if(remainingExamSeconds(run)===0){busy=false;await finish('time')}return}const c=run.competition,r=normalizeExamRules(c.examRules),now=Date.now(),pool=selectExamQuestions(api.questions,c,history,now);if(!pool.length)throw Error('Sem perguntas elegíveis para estes diplomas e âmbito.');const families=new Set(pool.map(q=>q.familyId||q.id)),essayPool=examEligible(api.questions,c.region,c.legislationIds,c.area,c.administrationScope,c.programme).filter(q=>String(q.questionType).includes('caso')&&!families.has(q.familyId||q.id)).sort((a,b)=>b.difficulty-a.difficulty||a.id.localeCompare(b.id)),essays=[];for(const q of essayPool){if(essays.length>=r.essayCount)break;const family=q.familyId||q.id;if(families.has(family))continue;families.add(family);essays.push(q)}
  if(essays.length<r.essayCount)throw Error('Não existem casos distintos suficientes para as respostas escritas; reduz a quantidade no concurso.');
  run={id:crypto.randomUUID(),competition:structuredClone(c),rules:r,status:'running',startedAt:new Date(now).toISOString(),deadline:r.durationMinutes?new Date(now+r.durationMinutes*60000).toISOString():null,readingSources:Object.fromEntries([...pool,...essays].map(q=>[q.law+':'+q.articleNumber,readingSources[q.law+':'+q.articleNumber]]).filter(([,s])=>s).map(([key,s])=>[key,structuredClone(s)])),questions:structuredClone(pool),questionIds:pool.map(q=>q.id),responses:{},flagged:{},essayQuestions:structuredClone(essays),essays:{},index:0};await persist();api.show();startTimer();
 }catch(err){api.alert('Simulado não iniciado: '+err.message)}finally{busy=false}}
 async function finish(reason='submit'){if(busy||run?.status!=='running')return;busy=true;try{
  const text=document.querySelector('#examEssay'),currentEssay=run.essayQuestions?.[run.index-run.questions.length];if(text&&currentEssay)run.essays[currentEssay.id]=text.value||'';
  if(reason!=='time'&&run.rules.essayLimitLines&&Object.values(run.essays).some(value=>value.split('\n').length>run.rules.essayLimitLines)){await persist();throw Error('Uma resposta excede o limite de '+run.rules.essayLimitLines+' linhas; o rascunho foi guardado.')} 
  if(reason!=='time'&&run.rules.essayLimitLines&&Object.values(run.essays).some(value=>value.split('\n').length>run.rules.essayLimitLines)){await persist();throw Error('Uma resposta excede o limite de '+run.rules.essayLimitLines+' linhas; o rascunho foi guardado.')} 
  const result={...structuredClone(run),status:'finished',finishedAt:new Date().toISOString(),finishReason:reason,score:scoreExam(run)},previous=api.reviews(),responses=[],reviews=[];
  for(const q of run.questions){const selected=run.responses[q.id];if(!Number.isInteger(selected))continue;const correct=selected===q.correct;responses.push({questionId:q.id,correct,selected,familyId:q.familyId||q.id,mode:'simulation',assisted:run.rules.consultation==='permitted',competitionId:run.competition.id,simulationId:run.id,answeredAt:result.finishedAt});reviews.push(nextReview(previous.find(r=>r.questionId===q.id),correct,q.id,Date.parse(result.finishedAt)))}
  const next=[...history.filter(h=>h.id!==result.id),result].slice(-30);await saveExamResult(next,responses,reviews);history=next;run=result;activeDraft=null;stopTimer();await api.reloadAnswers();api.show();
 }catch(err){api.alert('Resultado não guardado: '+err.message)}finally{busy=false}}
 function resultView(){const s=run.score;return '<h2>Simulado terminado</h2><p>'+s.correct+' certas · '+s.wrong+' erradas · '+s.blank+' em branco</p><p>Componente automática: <strong>'+s.automaticScore+'/'+s.automaticMaximum+'</strong>. '+(s.essayPending?'Respostas escritas aguardam autocorreção; não existe nota final automática.':'Nota de treino; não prevê a classificação de uma prova oficial.')+'</p>'+(!s.penaltyConfirmed?'<p>Penalização oficial por confirmar. Neste cálculo de treino, erros valem zero.</p>':'')+(run.finishReason==='time'?'<p>O tempo terminou. As respostas em branco valem zero neste treino.</p>':'')+run.questions.map(q=>'<details class="panel"><summary>'+e(q.prompt)+' · '+(run.responses[q.id]===undefined?'Em branco':run.responses[q.id]===q.correct?'Certa':'Errada')+'</summary><p>Resposta: '+e(q.options[q.correct])+'</p><p>'+e(q.explanation)+'</p>'+api.questionSource(q)+'</details>').join('')+run.essayQuestions.map(q=>'<section class="panel"><h3>Resposta escrita</h3><p>'+e(q.prompt)+'</p><p>'+e(run.essays[q.id]||'Não respondida')+'</p><details><summary>Conferir conteúdo e fundamentação</summary><p>'+e(q.explanation)+'</p>'+api.questionSource(q)+'<p>Verifica: norma e âmbito; factos e pressupostos; decisão justificada; estrutura, ortografia e clareza. Esta lista não reproduz uma grelha oficial do teu concurso.</p></details></section>').join('')+'<p>Resultado e texto guardados no dispositivo e no backup.</p><button class="btn" id="newExam">Preparar outro simulado</button>';}
 function view(){if(!run)return api.shell('<h2>Sem simulado</h2><button class="btn" data-nav="competitions">Voltar aos concursos</button>');
  if(run.status==='setup')return api.shell('<h2>Simulado — '+e(run.competition.title)+'</h2>'+examRulesSummary(run.competition,e)+'<p>As perguntas abrangem vários níveis. A correção fica oculta até entregares. '+(normalizeExamRules(run.competition.examRules).consultation==='permitted'?'Podes consultar os textos legais locais.':'Neste treino não aparece legislação durante as respostas.')+'</p><p>O relógio usa a hora real; sair da aplicação não interrompe o tempo. O último registo guardado permite retomar. Se houver menos famílias distintas do que a meta, a quantidade será reduzida.</p><button class="btn btn-dark" id="startExam">Iniciar simulado</button>');
  if(run.status==='finished')return api.shell(resultView());
  const count=run.questions.length,total=count+run.essayQuestions.length,essay=run.index>=count,q=essay?run.essayQuestions[run.index-count]:run.questions[run.index],choice=run.responses[q.id],reading=run.readingSources?run.readingSources[q.law+':'+q.articleNumber]:q.sourceEvidence?.text?{...q,text:q.sourceEvidence.text}:null;
  return api.shell('<section class="panel"><p id="examTimer" role="timer">'+clockText(remainingExamSeconds(run))+'</p><p>'+e(run.competition.title)+' · '+(essay?'Escrita':'Escolha única')+' '+(run.index+1)+'/'+total+'</p><h2>'+e(q.prompt)+'</h2>'+(essay?'<p>Explica a decisão, os pressupostos e o fundamento legal. '+(run.rules.essayLimitLines?'Limite de treino: '+run.rules.essayLimitLines+' linhas.':'')+'</p><textarea id="examEssay" rows="12">'+e(run.essays[q.id]||'')+'</textarea><p id="essaySaveStatus"></p>':q.options.map((text,i)=>'<button class="option '+(choice===i?'selected':'')+'" data-exam-answer="'+i+'" aria-pressed="'+(choice===i)+'">'+e(text)+'</button>').join('')+'<button class="btn" id="examClear">Deixar em branco</button>')+'<p><button class="btn" id="examFlag">'+(run.flagged[q.id]?'Retirar marca':'Marcar para rever')+'</button></p>'+(run.rules.consultation==='permitted'&&reading?'<details><summary>Consultar texto legal</summary><p class="reading-text">'+e(reading.text)+'</p>'+api.questionSource(reading)+'</details>':'')+'<p><button class="btn" id="examPrev" '+(run.index===0?'disabled':'')+'>Anterior</button> <button class="btn" id="examNext" '+(run.index===total-1?'disabled':'')+'>Seguinte</button></p><p>'+Object.keys(run.responses).length+'/'+count+' escolhas respondidas · '+Object.values(run.flagged).filter(Boolean).length+' marcadas</p><div class="exam-grid">'+Array.from({length:total},(_,i)=>{const item=i<count?run.questions[i]:run.essayQuestions[i-count],marked=run.flagged[item.id],done=i<count?Number.isInteger(run.responses[item.id]):Boolean(run.essays[item.id]);return '<button class="btn" data-exam-index="'+i+'" aria-label="Pergunta '+(i+1)+(marked?', marcada':'')+(done?', respondida':'')+'">'+(i+1)+(marked?' *':done?' ✓':'')+'</button>'}).join('')+'</div><button class="btn btn-dark" id="submitExam">Entregar e ver correção</button><p>As escolhas são guardadas ao selecionar. O texto é guardado enquanto escreves e ao mudar de pergunta ou entregar.</p></section>');
 }
 async function saveEssay(){if(run?.status!=='running'||run.index<run.questions.length)return;const node=document.querySelector('#examEssay'),q=run.essayQuestions[run.index-run.questions.length];if(node){const value=node.value||'',lines=value.split('\n').length;run.essays[q.id]=value;await persist();const status=document.querySelector('#essaySaveStatus');if(status)status.textContent=run.rules.essayLimitLines&&lines>run.rules.essayLimitLines?'Texto guardado; excede o limite de '+run.rules.essayLimitLines+' linhas.':'Texto guardado.'}}
 const guarded=fn=>()=>{changes=changes.then(async()=>{if(run?.status!=='running')return;changing=true;try{if(remainingExamSeconds(run)===0){await finish('time');return}await fn()}catch(err){api.alert('Alteração não guardada: '+err.message)}finally{changing=false}});return changes};
 function bind(){
  document.querySelectorAll('[data-apply-exam-preset]').forEach(button=>button.onclick=()=>{const form=button.closest('form'),preset=examPresets.find(p=>p.id===form.elements.examPreset.value);if(!preset||preset.id==='manual')return;const r=normalizeExamRules(preset.rules);for(const key of ['durationMinutes','consultation','officialFormat','questionCount','automaticPoints','wrongPenalty','essayCount','essayLimitLines'])form.elements[key].value=r[key]??'';form.elements.examSource.value=r.source;form.elements.examSourceNote.value=r.sourceNote;});
  document.querySelectorAll('[data-exam-rules-form]').forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();try{await api.updateRules(form.dataset.examRulesForm,readExamRules(form))}catch(err){api.alert('Regras não guardadas: '+err.message)}}));
  document.querySelectorAll('[data-exam]').forEach(b=>b.onclick=async()=>{const c=api.competitions().find(c=>c.id===b.dataset.exam);if(c)await enter(c)});
  document.querySelectorAll('[data-exam-result]').forEach(b=>b.onclick=()=>{const saved=history.find(h=>h.id===b.dataset.examResult);if(saved){run=structuredClone(saved);api.show()}});
  document.querySelector('[data-exam-resume]')?.addEventListener('click',async()=>{if(activeDraft)await enter(activeDraft.competition)});
  if(api.currentView()!=='exam')return;
  document.querySelector('#startExam')?.addEventListener('click',start);
  document.querySelector('#newExam')?.addEventListener('click',async()=>{const c=run.competition;await enter(c)});
  document.querySelectorAll('[data-exam-answer]').forEach(b=>b.onclick=guarded(async()=>{run.responses[run.questions[run.index].id]=Number(b.dataset.examAnswer);await persist();api.show()}));
  document.querySelector('#examClear')?.addEventListener('click',guarded(async()=>{delete run.responses[run.questions[run.index].id];await persist();api.show()}));
  document.querySelector('#examFlag')?.addEventListener('click',guarded(async()=>{const q=run.index<run.questions.length?run.questions[run.index]:run.essayQuestions[run.index-run.questions.length];run.flagged[q.id]=!run.flagged[q.id];await persist();api.show()}));
  const move=async index=>{await saveEssay();run.index=index;await persist();api.show()};
  document.querySelector('#examPrev')?.addEventListener('click',guarded(()=>move(run.index-1)));
  document.querySelector('#examNext')?.addEventListener('click',guarded(()=>move(run.index+1)));
  document.querySelectorAll('[data-exam-index]').forEach(b=>b.onclick=guarded(()=>move(Number(b.dataset.examIndex))));
  document.querySelector('#examEssay')?.addEventListener('change',guarded(saveEssay));
  document.querySelector('#examEssay')?.addEventListener('input',guarded(saveEssay));
  document.querySelector('#submitExam')?.addEventListener('click',guarded(async()=>{await saveEssay();await finish()}));
 }
 const historySummary=c=>history.filter(h=>h.competition.id===c.id).slice(-3).reverse().map(h=>'<p>'+e(h.finishedAt.slice(0,10))+' · '+h.score.automaticScore+'/'+h.score.automaticMaximum+' componente automática'+(h.score.essayPending?' · escrita por corrigir':'')+' <button class="btn" data-exam-result="'+e(h.id)+'">Rever respostas</button></p>').join('');
 const pendingSummary=()=>activeDraft?.status==='running'?'<section class="panel"><h3>Simulado em curso</h3><p>'+e(activeDraft.competition.title)+' · '+clockText(remainingExamSeconds(activeDraft))+'</p><button class="btn btn-dark" data-exam-resume>Retomar simulado em curso</button><p>O relógio continua a contar ao sair. O rascunho permanece acessível mesmo se o concurso for arquivado.</p></section>':'';
 return {load,enter,view,bind,historySummary,pendingSummary};
}
