const CACHE='concurso-study-v0.2-rh-ap-20261008-r23';
const ASSETS=['./','./index.html','./styles.css','./app.js','./db.js','./engine.js','./exam-mode.js','./exam-ui.js','./study-guide.js','./data/exam-references.js','./analytics.js','./learning.js','./article-memory.js','./essay.js','./guided-reading.js','./reading-excerpts.js','./data/reading-sources.js','./data/legal-context.js','./backup.js','./notifications.js','./offers.js','./data/bep-offers.json','./ATUALIZAR-BEP-RAM.html','./data/questions.js','./data/ap-questions.js','./data/reviewed-questions.js','./data/reviewed-part-01.js','./data/reviewed-part-02.js','./data/reviewed-part-03.js','./data/reviewed-part-04.js','./data/reviewed-part-05.js','./data/reviewed-part-06.js','./data/reviewed-part-07.js','./data/reviewed-part-08.js','./data/reviewed-part-09.js','./data/reviewed-part-10.js','./data/reviewed-part-11.js','./data/reviewed-part-12.js','./data/reviewed-part-13.js','./data/reviewed-part-14.js','./data/legacy-questions.js','./data/curriculum.js','./data/exam-curriculum.js','./data/legacy-curriculum.js','./data/legislation.js','./data/programmes.js','./data/coverage.json','./data/circulares-2025.json','./cobertura.html','./cobertura.js','./manifest.webmanifest','./icons/avatar.svg','./icons/apple-touch-icon.png','./icons/icon-192.png','./icons/icon-512.png'];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('concurso-study-')&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
 if(event.request.method!=='GET'||new URL(event.request.url).origin!==self.location.origin)return;
 if(new URL(event.request.url).pathname===new URL('./data/bep-offers.json',self.registration.scope).pathname){
  event.respondWith((async()=>{const cache=await caches.open(CACHE),key=new URL('./data/bep-offers.json',self.registration.scope).href;try{const response=await fetch(event.request);if(response.ok){await cache.put(key,response.clone());return response}}catch{}const saved=await cache.match(key);if(saved)return saved;return new Response('Ofertas indisponíveis',{status:503})})());return;
 }
 event.respondWith(caches.open(CACHE).then(async cache=>(await cache.match(event.request))||fetch(event.request)));
});
self.addEventListener('notificationclick',event=>{
 event.notification.close();event.waitUntil((async()=>{const url=new URL('./',self.registration.scope).href;const windows=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const window of windows)if(window.url.startsWith(self.registration.scope)){await window.focus();return}await self.clients.openWindow(url)})());
});
